### ISSUE TITLE
Oppgave- og ansvarstype

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#10]
PAS tilgjengeliggjør eksamensplanen gjennom _ExportTestDefinitionsFromPAS_ i dag. Har SAS systemene noen mulighet til å avgjøre om en faggkode er sentral/lokal gitt og sentral/lokal sensur?

**Comment by Sveinj** [comment]
IST henter den informasjonen fra GREP

**Comment by terje-barman** [comment]
Fra grep får vi feltet "Sensur" som angir om det er sentral eller lokal sensur, men det er ikke alle fagkoder som har noen verdi i feltet. Vi kunne satt lokal sensur som default, men vi har valgt å gi eksamensansvarlig ansvar til selv å bestemme om det skal være lokal eller sentral sensur ved opprettelse av eksamenspartier i iSkole.

**Comment by espenekvang** [comment]
Takk for info.
