### ISSUE TITLE
Javaeksempel

### ISSUE THREAD

**Issue by thomashannestad** [Utdanningsdirektoratet/PAS2-Public#13]
Hei,

vi har nå forsøkt å kjøre javaeksempelet rett ut av boksen uten endringer. Får følgende utskrift:
>Requesting autentication cookie
>null

Den ser ikke ut til å finne noen cookie i getAuthCookie.
For debug har jeg endret metoden til:
```java    
try{
      System.out.println("Con="+con);
      System.out.println(con.getContent());
    }
    catch(Exception e)
    {
      e.printStackTrace();
    }
    String headerField = con.getHeaderField("Set-Cookie");
    System.out.println("Header="+headerField);
    String[] cookies = headerField.split(";");
    for (String cookie: cookies)
    {
      if (cookie.startsWith("FedAuth"))
      {
        return cookie;
      }
    }
```

Dette gir følgende utskrift:
> Requesting autentication cookie
> Con=sun.net.www.protocol.https.DelegateHttpsURLConnection:https://eksamen-tst2.udir.no/api/ekstern/innlogging
> java.io.IOException: Server returned HTTP response code: 400 for URL: https://eksamen-tst2.udir.no/api/ekstern/innlogging
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
> 	at java.net.URLConnection.getContent(URLConnection.java:748)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:434)
> 	at Login.getAuthCookie(Login.java:242)
> 	at Login.login(Login.java:133)
> 	at Login.main(Login.java:83)
> Header=null
> null

**Comment by thomashannestad** [comment]
En liten detalj. ø'en i "issueRequestWithCookie(baseAddress, "/api/ekstern/skoler/1234/prøveperioder/432/kandidater", cookie);" medfører at vi må kompilere med option "-encoding ISO-8859-15"

**Comment by espenekvang** [comment]
Takk for tilbakemeldingen. JAVA eksempelet var ikke helt oppdatert etter at vi har introdusert eget miljø for SAS'ene. Eksempelet er nå oppdatert med riktig url mot testmiljøet. Når det gjelder æøå så vil det ikke være noen url'er i API'et som har disse bokstavene i seg nettopp pga detaljen du nevner. Eksempelet er derfor også oppdatert med en gyldig adresse som ikke inneholder æ,ø eller å.

**Comment by thomashannestad** [comment]
Kommer innholdet også til å kvitte seg med æ,ø,å? 
Ref: https://www.lucidchart.com/publicSegments/view/552e238f-b7e0-49f1-88a9-57d00a008aca/image.png

Utviklingsverktøyet vårt misliker æ,ø,å i variabelnavn og metoder. For at responsen skal mappes til klassene vi har opprettet må vi overstyre attributter med æ,ø,å. F.eks. (@JsonProperty("eksamenspåmeldinger")

**Comment by espenekvang** [comment]
Ok, da skal vi oppdatere slik at vi ikke benytter oss av æøå i selve kontraktene. Jeg gir beskjed når dette er ute i testmiljøet.

**Comment by thomashannestad** [comment]
Flott! Blir også skjemaene oppdatert slik at de ikke genererer javakode med ø,æ,å?

Vi har fylt opp klassene med noe data, konvertert til json og puttet over i en outputstream. Nå er vi litt i tvil om veien videre. Har dere mulighet til å skrive et java-eksempel som viser hvordan man kobler seg til og laster opp dette?

**Comment by espenekvang** [comment]
Skjemaene er nå oppdatert slik at de ikke inneholder æ,ø,å. Til informasjon vil vi operere med følgende oversettelse:
æ => ae
ø => o
å => a

Jeg skal se om vi kan lage et eksempel til dere rundt hvordan dere skal benytte ressursene. Som det står beskrevet på WIKI siden så aksepterer vi XML payload og ikke JSON inn til f.eks påmelding blant annet fordi vi ønsker å benytte xsd validering av dataene. Dersom du ønsker å få XML ut av ressursene i stedet for JSON som er standard, kan du sette Accept header til å være application/xml. Se [her] (https://github.com/Utdanningsdirektoratet/PAS2-Public/wiki/03.-SAS-Integrasjon) for detaljer rundt dette.

**Comment by thomashannestad** [comment]
Dukket opp en å til. Denne er i responsen fra kandidatpåmeldinga.

javax.xml.bind.UnmarshalException: unexpected element (uri:"http://schemas.datacontract.org/2004/07/UDIR.PAS2.Web.Models.P%C3%A5melding", local:"PåmeldingReference"). Expected elements are <{http://www.w3.org/2001/XMLSchema}PameldingReference>

**Comment by espenekvang** [comment]
Dette er fikset nå.
