### ISSUE TITLE
Er tjenesten nede?

### ISSUE THREAD

**Issue by thomashannestad** [Utdanningsdirektoratet/PAS2-Public#17]
Er det noen problemer med https://eksamen-sas.udir.no? Får ikke logget inn lenger.

Har forsøkt med å gå tilbake og kjøre java-eksempelet, det skriver følgende:

>Requesting autentication cookie
>null

**Comment by vidarkongsli** [comment]
Ser ut som vi har litt problemer i dette miljøet. Jeg skal se på det.

**Comment by vidarkongsli** [comment]
Eksempelklienten er ikke oppdatert ihht. [LogIn.xsd](https://eksamen-sas.udir.no/api/ekstern/skjema) og derfor returnerer serveren 400 bad request. 
Vi skal oppdatere eksempelklientene.
cc @espenekvang @Thor-Kristian-Valderhaug

**Comment by Thor-Kristian-Valderhaug** [comment]
Jeg kan oppdatere klienten. Sier i fra når ny versjon er lagt ut

**Comment by espenekvang** [comment]
Flott @Thor-Kristian-Valderhaug

**Comment by Thor-Kristian-Valderhaug** [comment]
Da skal java-eksempelet være oppdatert og fungere igjen. @thomashannestad si fra hvis du fortsatt her problemer

**Comment by thomashannestad** [comment]
Får kontakt med tjenesten igjen nå. Fikk problemer med xml-mapping for "/api/ekstern/kandidat?orgno=874546852&periodekode=H-2015".

Javakoden som ble generert av xsd-filene benytter navn Kandidatgruppeansvarlige, mens tjenesten leverer KandidatGruppeAnsvarlige. JAXB er tydeligvis case-sensitive, har ikke undersøkt om den kan gjøres case-insensitive. 

I en del av javafilene som blir generert mangler xml-informasjon om namespace. Dette skaper også problemer med mapping mellom xml og java. Eks:
```xml
@XmlType(name = "PameldtKandidatgruppeType", namespace="http://pas.udir.no/Pamelding", propOrder = {
    "navn",
    "kandidatgruppeansvarlige",
    "kandidater"
})
```

**Comment by terje-barman** [comment]
Hei!

Hvis dere konsekvent lar alle navn være lowercase så blir det litt vanskeligere å lese, men man slipper feil som dette.

​Vennlig hilsen
Terje Barman
-------------------------------------------------
Barman Hanssen AS
Epost: terje@barman-hanssen.no <mailto:terje@barman-hanssen.no>
Mob.: 0047 993 98 715
Skype: terje.barman

**Comment by aoksenholt** [comment]
JSON-responsen leverer denne propertien i Lower Camel Case (kandidatGruppeAnsvarlige), resten i lower case.

I eksamensplan-api'et er det ikke samsvar mellom skjema og respons. Skjema har fortsatt noen norske tegn, responsen leverer med ø=o osv. (f.eks EksamensdelType->GjennomføringStart kommer tilbake som gjennomforingStart)

**Comment by espenekvang** [comment]
Kandidatgruppeansvarlig er nå med lowervase og ø er fjernet fra gjennomføringstart i xsd. Rullet ut til testmiljøet
