### ISSUE TITLE
XSD til Java

### ISSUE THREAD

**Issue by thomashannestad** [Utdanningsdirektoratet/PAS2-Public#18]
Har gitt noen tilbakemeldinger her og noen på e-post m.t.p javaobjektene som genereres fra skjemaene. Her kommer en oppsummering av endringene vi har måttet gjøre for å kunne lese ut kandidater og melde på kandidater.

**EksamensdelType.java:**
ø må bort.
gjennomføringStart
gjennomføringSlutt

**package-info.java:**

La til alle namespace, ikke bare pamelding.
 ```java
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2001/XMLSchema", 
                                     xmlns = {
                                     @XmlNs(namespaceURI = "http://pas.udir.no/Pamelding", prefix = "pa"),
                                     @XmlNs(namespaceURI = "http://pas.udir.no/Eksamensplan", prefix = "ep"),
                                     @XmlNs(namespaceURI = "http://pas.udir.no/CommonTypes", prefix = "ct"),
                                     },
                                     elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
import javax.xml.bind.annotation.XmlNs;
```

**PameldteKandidater.java:**
La til namespace i XmlRootElement

 ```java
@XmlRootElement(name = "PameldteKandidater", namespace="http://pas.udir.no/Pamelding")
```

Tok bort namespace="" for:
 ```java
 @XmlElement(name = "Eksamensperiodekode", required = true)
    protected String eksamensperiodekode;
    @XmlElement(name = "Eksamenspameldinger", required = true)
    protected EksamenspameldingerType eksamenspameldinger;
```
La til name og namespace for XmlType:
 ```java
@XmlType(name = "PameldteKandidater", namespace="http://pas.udir.no/Pamelding", propOrder = {
```

**EksamenspameldingType.java:**
Tok bort namespace="" for
 ```java
    @XmlElement(name = "Fagkode", required = true)
    protected String fagkode;
    @XmlElement(name = "Kandidatgrupper", required = true)
    protected PameldteKandidatgrupperType kandidatgrupper;
```
La til namespace for: 
 ```java
@XmlType(name = "EksamenspameldingType", namespace="http://pas.udir.no/Pamelding", propOrder = {
```
**PameldteKandidatgrupperType.java:**
La til namespace i
 ```java
@XmlType(name = "PameldteKandidatgrupperType", namespace="http://pas.udir.no/Pamelding", propOrder = {
```
Tok vekk namespace="" for 
 ```java
@XmlElement(name = "Kandidatgruppe")
```

**PameldtKanidatgruppeType.java:**
La til namespace for 
 ```java
@XmlType(name = "PameldtKandidatgruppeType", namespace="http://pas.udir.no/Pamelding", propOrder = {
```
Tok vekk namespace="" for @XmlElement’ene

**PameldteKandidaterType.java:**
La til namespace for 
 ```java
@XmlType(name = "PameldteKandidaterType", namespace="http://pas.udir.no/Pamelding", propOrder = {
```
Tok vekk namespace "" for 
 ```java
@XmlElement(name = "Kandidat")
```

**PameldtKandidatType.java:**
La til namespace for 
 ```java
@XmlType(name = "PameldtKandidatType", namespace="http://pas.udir.no/Pamelding", propOrder = {
```
Tok vekk namespace="" for @XmlElement’ene

Endret Kandidattype til liten «t» i type
 ```java
@XmlElement(name = "Kandidattype", required = true)
```

**Pamelding.java**
name og namespace lagt til for:
 ```java
@XmlType(name = "Pamelding", namespace="http://pas.udir.no/Pamelding", propOrder = {
```
namespace lagt til for
 ```java
@XmlRootElement(name = "Pamelding", namespace="http://pas.udir.no/Pamelding")
```

**KandidatgrupperType.java:**
La til namespace for 
 ```java
@XmlType(name = "KandidatgrupperType",namespace="http://pas.udir.no/Pamelding", propOrder = {
```

**KandidatgruppeType.java:**
La til namespace for 
 ```java
@XmlType(name = "KandidatgruppeType",namespace="http://pas.udir.no/Pamelding", propOrder = {
```
**KandidaterType.java:**
La til namespace for 
 ```java
@XmlType(name = "KandidaterType",namespace="http://pas.udir.no/Pamelding", propOrder = {
```
**KandidatType.java:**
La til namespace for
 ```java
@XmlType(name = "KandidatType",namespace="http://pas.udir.no/Pamelding", propOrder = {
```

**PameldingReference.java:**
Her har jeg ikke gjort noen endringer, men mapping mot denne krasjer fordi xml fra PAS inneholder å i PåmeldingReference.

**Comment by espenekvang** [comment]
Tusen takk for grundig tilbakemelding. Vi går gjennom og gir tilbakemelding når ny versjon er ute i testmiljøet.

**Comment by espenekvang** [comment]
Justeringer for æøå som er nevnt i denne tråden er nå rullet ut til testmiljøet. Alle manuelle tillegg du har gjort for namespace justeringer er foreløpig ikke håndtert.

**Comment by thomashannestad** [comment]
PåmeldingReference er nå uten å og vi er kommet litt videre.

**KandidatgruppeReportsType.java**
La til namespace for xmlType og la til Report @XmlElement(name= "KandidatgruppeReport")

```java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KandidatgruppeReportsType",namespace="http://pas.udir.no/Pamelding", propOrder = {
    "kandidatgruppe"
})
public class KandidatgruppeReportsType {

    @XmlElement(name = "KandidatgruppeReport")
    protected List<KandidatgruppeReportType> kandidatgruppe;
```

Tilsvarende endring i **KandidatReportsType.java** og **KandidatgruppeansvarligReportsType.java**

Ellers ser det ut til at vi slipper unna alle namespacefeilene ved å endre default namespace i **package_info.java**

```java
@javax.xml.bind.annotation.XmlSchema(namespace = "http://pas.udir.no/Pamelding", 
                                     xmlns = {
                                     @XmlNs(namespaceURI = "http://pas.udir.no/Pamelding", prefix = "pa"),
                                     @XmlNs(namespaceURI = "http://pas.udir.no/Eksamensplan", prefix = "ep"),
                                     @XmlNs(namespaceURI = "http://pas.udir.no/CommonTypes", prefix = "ct"),
                                     },
                                     elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bh.iskole.pas2.types;
```

**Comment by espenekvang** [comment]
Ok, Report skal ikke være nødvendig å legge inn så det er testmiljøet oppdatert med nå.

Forstår jeg deg riktig at ved å legge til default namespace i package_info.java løste de tidligere problemene du hadde med namespace seg?

**Comment by thomashannestad** [comment]
Ja, da vi hadde kjørt alle xsd-filene samlet gjennom xjc ble package-info.java generert slik:

```java
@javax.xml.bind.annotation.XmlSchema(namespace = "http://pas.udir.no/Pamelding", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
```

Der mangler CommonTypes og Eksamensplan. Vet ikke om det er noen måte å kjøre xjc på slik at package-info.java inneholder alle namespace som blir benyttet?

Vi endret den derfor denne manuelt slik den ser ut øverst i første innlegg. Ved senere å endre default namespace slik som i siste innlegg, så løste dette problemene vi hadde med namespace.

**Comment by thomashannestad** [comment]
Har hentet ut oppdaterte skjemaer og generert javaklasser. Er fortsatt mange attributter som er generert med namespace="". Dette gjelder spesielt ved uthenting av kandidater(/api/ekstern/kandidat?orgno=874546852&periodekode=H-2015) 

namespace="" medfører følgende feil for javax.xml.bind.Unmarshaller:

```quote
Internal Exception: org.xml.sax.SAXParseException; lineNumber: 51; columnNumber: 15; unexpected element (uri:"http://pas.udir.no/Pamelding", local:"Fodselsnr"). Expected elements are <{}Fodselsnr>,<{}Fornavn>,<{}Etternavn>,<{}Malform>,<{}Kandidattype>,<{}Kandidatnummer>
```

Eksempel **PameldtKandidatType.java**:
```java
@XmlElement(name = "Kandidatnummer", namespace = "", required = true)
```

**Comment by aoksenholt** [comment]
Vi (IST) skriver også i Java, men har benyttet json, ikke XML, da slipper man JAXB-problemer etc..

**Comment by thomashannestad** [comment]
Takk for tips!

I dokumentasjonen står det:
Ressurs: ~/api/ekstern/kandidatpamelding

 <https://github.com/Utdanningsdirektoratet/PAS2-Public/wiki/03.-SAS-Integrasjon#verb-post-1>Verb: POST

Foreta påmelding med XML payload som beskriver kandidatene som skal meldes på.


Vi antok derfor at påmelding måtte gjøres med XML. Den godtar altså JSON dersom vi spesifiserer det i headeren?


Med vennlig hilsen
Thomas Hannestad
Barman Hanssen AS
thomas@barman-hanssen.no

**Comment by espenekvang** [comment]
Tjenestene vil returnere JSON dersom man spesifiserer det, men vi aksepterer kun XML inn til ressursene.

**Comment by aoksenholt** [comment]
Selve payload som sendes i Påmelding må vel være XML som dok'en sier, men har ikke opplevd noen problemer rundt den (all payload skal vel være XML).

Vi har spesisfisert at respons skal være JSON (man kan velge).

**Comment by thomashannestad** [comment]
Var derfor vi tenkte at vi like gjerne kunne bruk XML til alt, fremfor å forholde oss både til JSON og XML. Visste ikke at det skulle by på ekstra utfordringer.
