### ISSUE TITLE
Allerede påmeldte kandidater

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#19]
Vi har fått tilbakemelding på at dersom man forsøker å gjennomføre en identisk påmelding flere ganger etter hverandre vil man få "Kandidaten er allerede påmeldt". Vi jobber med en løsning nå som gjør at siste påmelding vil "vinne" og at man skal få tilbake kandidatnummeret som den har fått. Eventuelle endringer i navn og kontaktinformasjon på kandidaten vil bli oppdatert.

Virker det greit ref. dagens implementasjon?

**Comment by aoksenholt** [comment]
Det er veldig ønskelig med en løsning hvor siste påmelding "vinner" og at kandidatnummer alltid kommer i retur.

**Comment by espenekvang** [comment]
Da er dette implementert og rullet ut i testmiljøet.
