### ISSUE TITLE
Hente ut eksamensplan

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#20]
Vi har fått rapportert inn problemer rundt å hente ut eksamensplan og unmarshalling av dette for JAVA klienter. På grunn av dette er responsen man får tilbake når man henter ut eksamensplan endret til å returnere en EksamensplanResponse som igjen inneholder en liste av Eksamensplaner. 

Endringene er rullet ut til SAS-miljøet.

Vi håper det kan løse problemene man har opplevd.

**Comment by aoksenholt** [comment]
Beklager treg tilbakemelding, men kan ikke se at JSON-representasjonen av Eksamensplaner er en liste av EksamensplanType

Respons nå

**{**"eksamensplaner":[{"opplaeringsniva":"VGS","eksamensperiode":{"kode":"H-2015","pameldingStart":"2015-04-01T02:00:00","pameldingStopp"...

Skal være?

**{[**"eksamensplaner":[{"opplaeringsniva":"VGS","eksamensperiode":{"kode":"H-2015","pameldingStart":"2015-04-01T02:00:00","pameldingStopp"...
