### ISSUE TITLE
Karakteroversikt

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#24]
Vi har startet med arbeidet å definere datamodellen for eksport av karakterer fra eksamenssystemet til skoleadministrative systemer. På [denne] (https://www.lucidchart.com/publicSegments/view/be8d21f1-717a-4a83-b0e0-576d560e3839/image.png) linken er et utkast til hvordan denne modellen kan se ut.

Kan vi få tilbakemelding på følgende spørsmål:

1. Spør man alltid om resultater kun på en fagkode av gangen eller ønsker man å få resultater på alle fagkoder på en gitt skole?
2. Er det noe som mangler i den foreslåtte modellen? Felter som dere benytter som ikke lenger er der?

@aoksenholt @thomashannestad

**Comment by terje-barman** [comment]
Hei!

Ang. punkt 2.

Vi tenkte i utgangspunktet å ta inn alle resultatene skolevis uten å måtte oppgi fagkode. Ellers ser det ut til at vi ikke skulle mangle noe.

​Vennlig hilsen
Terje Barman
-------------------------------------------------
Barman Hanssen AS
Epost: terje@barman-hanssen.no <mailto:terje@barman-hanssen.no>
Mob.: 0047 993 98 715
Skype: terje.barman

**Comment by espenekvang** [comment]
Ok, takk for innspill. Da skal vi se på muligheten for å hente ut på skolenivå, men med mulighet for å hente på fagkode dersom man ønsker det.
