### ISSUE TITLE
XSD-skjemaer

### ISSUE THREAD

**Issue by mhjelmseth** [Utdanningsdirektoratet/PAS2-Public#25]
Hvor kan jeg finne LogIn.xsd og DigitalSignature.xsd som dere refererer til i dokumentasjonen for ~/api/ekstern/innlogging. Kan ikke se at disse eksisterer i zip-filen med skjemaer som jeg har hentet fra ~/api/ekstern/skjema.

mvh
Morten Hjelmseth
Visma Software Labs AS

**Comment by espenekvang** [comment]
Takk for tilbakemelding. Det har blitt gjort en omstrukturering og de to skjemaene har dessverre ikke blitt inkludert i ZIP-filen etter omstruktureringen. Jeg har midlertidig lastet opp ZIP-filen til deg [her](https://github.com/Utdanningsdirektoratet/PAS2-Public/tree/master/ExampleClients) slik at du kan jobbe videre. Vi har også fikset slik at ZIP-filen vil inneholde XSD'ene du savner, men det vil ikke bli tilgjengelig i API'et før torsdag.

LogIn.xsd har fått nytt navn og heter nå LogInPasApp.xsd.

**Comment by mhjelmseth** [comment]
Strålende, tusen takk :)

Burde sikkert ha opprettet en ny issue på dette, men vi har også et testsertifikat vi ønsker å bruke i testsammenheng. Hvor sender jeg det?

**Comment by espenekvang** [comment]
Det kan du sende til meg. espen.ekvang@utdanningsdirektoratet.no
