### ISSUE TITLE
 /api/ekstern/kandidat?orgno=<orgNummer>&periodekode=<periodekode>

### ISSUE THREAD

**Issue by asands** [Utdanningsdirektoratet/PAS2-Public#26]
Hei,

Får en feilmelding fra endpoint  /api/ekstern/kandidat?orgno=<orgNummer>&periodekode=<periodekode>

Failed to process request. Exception logged on server with reference b0dbb907-5686-4aac-863e-1bef58ea0ce2. Contact PAS system administrators

Har dere mulighet til å se på loggen på deres side?

Mvh,

Andrew (Visma)

**Comment by espenekvang** [comment]
Det skal vi se på.
Gir deg tilbakemelding så fort vi har funnet ut noe.

**Comment by espenekvang** [comment]
Da kan du prøve på nytt.
