### ISSUE TITLE
Opplaeringsniva av typen GS

### ISSUE THREAD

**Issue by mhjelmseth** [Utdanningsdirektoratet/PAS2-Public#27]
api/ekstern/eksamensplan ser bare ut til å levere eksamensplan med opplaeringsniva = VGS

Er det mulig å få lagt inn en med opplaeringsniva = GS i test?

**Comment by espenekvang** [comment]
Foreløpig har vi kun eksamensplan for VGS, vi gir beskjed så fort vi har planen for GS tilgjengelig.

**Comment by espenekvang** [comment]
Vi har nå oppdatert testmiljøet med en forenkelt eksamensplan for opplæringsnivå grunnskole. Denne planen er som sagt ikke komplett, men gir dere mulighet til å starte testingen.

Ressursen for å hente eksamensplan: ~/api/ekstern/eksamensplan har nå støtte for filtrering på eksamensperiode og opplæringsnivå på følgende måte:

~/api/ekstern/eksamensplan?eksamensperiode=V-2016&opplaeringsniva=VGS

Mulige verdier for eksamensperiode er H-2015 og V-2016
Mulige verdier for opplaeringsnivå er VGS og GS

Dette er kun tilgjengelig i miljøet https://eksamen-sas.udir.no
