### ISSUE TITLE
Savner karaktertype (gamle MarkType) i KandidatMedKarakterType

### ISSUE THREAD

**Issue by aoksenholt** [Utdanningsdirektoratet/PAS2-Public#28]
I "gamle PAS" så finnes Student.MarkType som forteller om det f.eks er en klagekarakter. Kan ikke finne tilsvarende igjen i ny modell - er det bevisst eller er det en mangel?

**Comment by espenekvang** [comment]
Det er på vei ut en utvidelse som skal gi dere både Klagekarakter og Klagebegrunnelse.

**Comment by aoksenholt** [comment]
Takk for rask respons!

**Comment by espenekvang** [comment]
Du kan se i testmiljøet (https://eksamen-sas.udir.no/api/ekstern/skjema så ligger denne endringen for XSD Karakteroversikt. Det vil etter all sannsynlighet blir lagt i produksjon i løpet av kvelden i morgen. Da vil vi oppdatere dokumentasjonen her også.

**Comment by WISove** [comment]
Ah, der var lenken til oppdaterte xsd'er:) Fant bare xsd'er under eksempelkoden. Hadde vært lurt og lagt denne lenken inn i wikien...
Ove.

**Comment by espenekvang** [comment]
Ja, jeg har akkurat oppdatert wikien nå.
