### ISSUE TITLE
Testmiljø (https://eksamen-tst2.udir.no)

### ISSUE THREAD

**Issue by aoksenholt** [Utdanningsdirektoratet/PAS2-Public#29]
Hei

Er ikke lengre testmiljøet åpent for alle organisasjonsnummer? Får denne i return ved forsøk på påmelding (med orgno som tidligere har gått fint)

```
1 * Client in-bound response
1 < 401
1 < 
{"message":"Your organization is not known to us","data":null}
```

**Comment by espenekvang** [comment]
Prøv å benytte https://eksamens-sas.udir.no

**Comment by espenekvang** [comment]
For skoleadministrative systemer ønsker vi primært at man skal benytte https://eksamen-sas.udir.no. Jeg har fjernet det andre testmiljøet nå fra miljøoversikten på WIKI så ikke det skaper forvirring i fremtiden.
