### ISSUE TITLE
Lengde på fagkoder?

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#30]
Hvilke konsekvenser vil det ha for dere om fagkoden blir lengre enn 7 tegn slik den er i dag?

F.eks i dag ser fagkodene slik ut: REA3015, vi ser på muligheten for å inkludere mer informasjon i en fagkode, f.eks REA3015JAV.
Dette betyr at når man skal melde på må man oppgi den nye fagkoden som man vil få tilgang til gjennom https://eksamen.udir.no/api/ekstern/eksamensplan.​

**Comment by terje-barman** [comment]
Hei!

På generelt grunnlag vil jeg si det er uheldig å legge logikk inn i nøkler. Er det ikke mulig å la dette være et eget felt?

​Vennlig hilsen
Terje Barman
-------------------------------------------------
Barman Hanssen AS
Epost: terje@barman-hanssen.no <mailto:terje@barman-hanssen.no>
Mob.: 0047 993 98 715
Skype: terje.barman

**Comment by espenekvang** [comment]
Jeg er enig med deg i det og det er også et alternativ. Vi undersøker bare mulighetene nå, det er ikke utenkelig at fagkodene kan bli lengre enn 7 tegn slik det er nå og da er det greit å vite om det eventuelt vil skape noen problemer.

**Comment by aoksenholt** [comment]
Fra IST.

> I utgangspunktet støttes Terje Barnan Hanssens betenkning. Eventuelle andre konsekvenser kan gjelde vitnemål som krever mye data innen rammen av A4. En økning av antall tegn i fagkode vil kunne bety omprogrammering av vitnemål, og eventuelt problemer med å få plass til f.eks. FAM med to språkkoder, (FAM41) 
Ettersom fagkodene er gjennomgående og benyttes av flere samarbeidende programmer, ville det være ønskelig at en klarte å finne andre løsninger enn utvidelse av koden

**Comment by espenekvang** [comment]
Flott! Takk for raske svar
