### ISSUE TITLE
Ny statuser for deltagerstatus

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#31]
Vi har oppdatert dokumentasjonen for status når det kommer til hva slags statuser en kandidat kan ha fått. Dette gjelder ressursen api/ekstern/karakteroversikt. Wiki-siden inneholder link til bilde som beskriver modellen og den nye statusen

**Comment by thomashannestad** [comment]
Er det slik å forstå at de har skiftet navn fra Deltatt til D, IkkeDokumentertFravaer til IDF osv.? Det er ikke lagt til noen nye statuser?


Med vennlig hilsen
Thomas Hannestad
Barman Hanssen AS
thomas@barman-hanssen.no

**Comment by espenekvang** [comment]
Det stemmer. Alle statuser står her:

https://www.lucidchart.com/publicSegments/view/0b78aa10-386b-4699-b562-c3ef1c1d64ba/image.png
