### ISSUE TITLE
Varianter av fagkoder

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#32]
For våren 2016 vil det være et fag (REA3015) der det vil bli mulighet for å velge varianter. Mye av grunnen er for å lette sensuren for dette. 

Vi jobber med å få dette på plass nå og det vil få følgende konsekvenser for integrasjonen mot skoleadministrative systemer:

- eksamensplanen vil inneholde et nytt felt for de fagkodene som har varianter
- ved påmelding til fagkoder med variant skal man også sende med hvilken variant av faget man ønsker å melde kandidaten på til.
- påmeldingsrapporten vil få variant sammen med fagkoden
- karakteroversikt vil få variant sammen med fagkoden
- påmeldingsoversikten på en skole vil få variant med fagkoden

Varianten vil sendes over i et eget nytt felt som blir et frivillig felt siden det kun er en fagkode som vil operere med dette i våres.

Noen kommentarer til dette?

**Comment by aoksenholt** [comment]
Hva kan/vil variantfeltet inneholde?

**Comment by espenekvang** [comment]
For REA3015 vil den inneholde:

- JAV, som representerer Informasjonsteknologi 2 Java
- AS, som representerer Informasjonsteknologi 2 Action Script
- CS, som representerer Informasjonsteknologi 2 C Sharp
- DIV, som representerer Informasjonsteknologi 2 diverse språk

**Comment by WISove** [comment]
Hei,

Kan dere oppdatere xsd'ene her: https://github.com/Utdanningsdirektoratet/PAS2-Public/blob/master/ExampleClients/PAS2_skjemaer.zip

Er det en epostliste en kan melde seg på for å få melding om endring i api'et?

**Comment by espenekvang** [comment]
Eventuelle endringer vil kommuniseres her på github. 

For å ha tilgang på oppdaterte xsd så bør man benytte denne:

http://eksamen.udir.no/api/ekstern/skjema

**Comment by espenekvang** [comment]
Minner om at påmelding til REA3015 må inneholde varianter for våren 2016.

**Comment by AMNytroen** [comment]
Vil varianter i matematikk skriftlig for grunnskolen håndteres på samme måter?
Hvor i API skal variantene legges inn?

**Comment by Sveinj** [comment]
Er det noen begrensninger i feltlengde på Variant? 
Er det pt flere enn fag enn REA3015 som har Varianter? 
Hvordan distribueres informasjon om tillatte Varianter i fag?

**Comment by espenekvang** [comment]
Jeg har forsøkt å svare på spørsmålene deres her:

1. Foreløpig er det kun REA3015 som har varianter.
2. Varianten spesifiseres sammen med fagkoden når man melder på en kandidat
3. Det er foreløpig ingen begrensning i feltlengden
4. Dersom en fagkode har variant vil man kunne se disse variantene når man henter ut eksamensplanen gjennom api/ekstern/eksamensplan

**Comment by AMNytroen** [comment]
Av det du skriver over under pkt 1.kan det tyde på at det kun finnes variantkoder på REA3015.
Tidligere år har det vært variantkoder TEG, LSA,NSA og SSA på MAT0010 for grunnskoleeksamen (GS). Skal de ikke lenger være i bruk eller bare ikke implementert i testmiljøet ennå?
Hvordan spesifiseres varianten sammen med fagkoden ref pkt 2. over?

**Comment by espenekvang** [comment]
Jeg har sendt spørsmålet ditt videre til produkteierteamet. Så fort jeg hører fra de så legger jeg ut svar her.

**Comment by AMNytroen** [comment]
Takk

Anne Mari


Fra: Espen Ekvang [mailto:notifications@github.com]
Sendt: 5. januar 2016 21:00
Til: Utdanningsdirektoratet/PAS2-Public <PAS2-Public@noreply.github.com>
Kopi: Anne Mari Nytrøen <annytr@oppad.no>
Emne: Re: [PAS2-Public] Varianter av fagkoder (#32)


Jeg har sendt spørsmålet ditt videre til produkteierteamet. Så fort jeg hører fra de så legger jeg ut svar her.

**Comment by espenekvang** [comment]
Det er ikke varianter på eksamen utenom REA3015 foreløpig. De variantene du viser til gjelder nasjonale prøver.

Når det er sagt vil det komme flere varianter for eksamen når man skal støtte lokal/lokal fagkoder.

**Comment by AMNytroen** [comment]
Så vi trenger ikke legge opp til varaintkoder for eksamen grunnskole denne gangen?

Mvh
Anne Mari
Support


Fra: Espen Ekvang [mailto:notifications@github.com]
Sendt: 7. januar 2016 10:09
Til: Utdanningsdirektoratet/PAS2-Public <PAS2-Public@noreply.github.com>
Kopi: Anne Mari Nytrøen <annytr@oppad.no>
Emne: Re: [PAS2-Public] Varianter av fagkoder (#32)


Det er ikke varianter på eksamen utenom REA3015 foreløpig. De variantene du viser til gjelder nasjonale prøver.

Når det er sagt vil det komme flere varianter for eksamen når man skal støtte lokal/lokal fagkoder.

**Comment by espenekvang** [comment]
Det er riktig. Varianter er foreløpig kun for REA3015 videregående.

**Comment by AMNytroen** [comment]
Tusen takk ☺

Mvh
Anne Mari
Support


Fra: Espen Ekvang [mailto:notifications@github.com]
Sendt: 7. januar 2016 10:14
Til: Utdanningsdirektoratet/PAS2-Public <PAS2-Public@noreply.github.com>
Kopi: Anne Mari Nytrøen <annytr@oppad.no>
Emne: Re: [PAS2-Public] Varianter av fagkoder (#32)


Det er riktig. Varianter er foreløpig kun for REA3015 videregående.
