### ISSUE TITLE
Påmelding

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#33]
Vi forsøker å lage et klientbibliotek vha RestSharp, og etter litt kåling med serialisering etc ser det rent tekniske ut til å fungere sånn noenlunde. 

For utforske Pas2 REST Api, eget wrapper api og feilhåndteringsregime forsøker vi å melde opp kandidater, men får feilmeldinger. Finnes det noen oversikt over hvilke datakombinasjoner som burde virke?

Feilmelding: 

```xml
<?xml version="1.0" encoding="utf-8"?>
<pa:ApiError xmlns:ct="http://pas.udir.no/CommonTypes" xmlns:ko="http://pas.udir.no/Karakteroversikt" xmlns:ep="http://pas.udir.no/Eksamensplan" xmlns:pa="http://pas.udir.no/Pamelding">
  <pa:Message>Du forsøker å melde på kandidater til: Eksempel skole og oppgir organisasjonsnummeret: 875561162. Vi kjenner ikke igjen dette organisasjonsnummeret. Vennligst kontroller at dette er organisasjonsnummeret til skolen du forsøker å melde på.</pa:Message>
</pa:ApiError>
```

**Comment by espenekvang** [comment]
Vi importerer skoler fra NSR (Nasjonalt Skoleregister) hver natt og tilgjengeliggjør de basert på hva NSR sier. Organisasjonsnummeret du har oppgitt får vi ikke inn fra NSR og er derfor ikke tilgjengelig. Organisasjonsnummeret tilhører Stiftelsen Oslo Katedralskole, hvis du ønsker å melde på til Oslo Katedralskole er det riktige orgnanisasjonsnummeret 874590932. Oversikt over skoler kan du finne ved å gå inn på http://nsr.udir.no.

**Comment by thoraj** [comment]
Takk for svar,

Vi driver med **utvikling og test** av Pas2 integrasjonen, og ønsker ikke å melde opp kandidater skarpt nå. Er det riktig å bruke  https://eksamen-sas.udir.no ?

Hvis denne url'en er mot et testmiljø; kan vi da velge skoler vi tester mot fritt?

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Det er riktig å benytte https://eksamen-sas.udir.no. Det er et testmiljø som oppdateres fortløpende med funksjonalitet. Det er fint om dere melder fra til meg hvilken skole dere ønsker å melde på til.

**Comment by thoraj** [comment]
Kanskje like greit å teste en "Oppadskole", så da tenker jeg vi kjører litt tester mot Ajer (875270532).

Må dere legge inn noe før jeg kan regne med at dette fungerer?

**Comment by espenekvang** [comment]
Hvis du planlegger å benytte eget virksomhetssertifikat så vil jeg gjerne at du sender meg organisasjonsnummeret som står i det virksomhetssertifikatet på epost.

**Comment by thoraj** [comment]
Prøvde nettop mot Ajer (875270532), men fikk feilmeldingen:

```xml
<?xml version="1.0" encoding="utf-8"?>
<pa:ApiError xmlns:ct="http://pas.udir.no/CommonTypes" xmlns:ko="http://pas.udir.no/Karakteroversikt" xmlns:ep="http://pas.udir.no/Eksamensplan" xmlns:pa="http://pas.udir.no/Pamelding">
  <pa:Message>Du er authorisert for tilgang til skole med orgno 875561162, men forsøker å få tilgang til skole med orgno 875270532.</pa:Message>
</pa:ApiError>
```

Så da venter jeg til dere har "klarert" Ajer før jeg fortsetter.

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Det er viktig at du har samme organisasjonsnummer i POST dataene som du sender inn ved pålogging til api/ekstern/innlogging/ som du senere forsøker å gjøre operasjoner på. Cookien du får utdelt er kun gyldig på det organisasjonsnummeret du har oppgitt ved innlogging

**Comment by thoraj** [comment]
Hm. OK så la meg sjekke om jeg har forstått dette riktig:

 - Vi må registrere SAS selskapet (Oppad) hos dere med et virksomhetssertifikat. Dette sertifikatet er relatert til et organisasjonsnummer, men det er **ikke** det organisasjonsnummeret vi skal bruke i ClientIdentification?

 - I ClientIdentification oppgir vi organisasjonsnummeret for den skolen vi skal gjøre påmeldinger/spørringer på vegne av?

Er dette riktig forstått?

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Det er riktig. Siden hver skole ikke skal kunne trenge sitt eget virksomhetssertifkat så er virksomhetssertifiaktet knyttet til leverandøren av det skoleadministrative systemet, mens organisasjonsnummeret man oppgir i ClientIdentification er skolen man gjøre integrasjon mot eksamenstjenesten fra.

**Comment by thoraj** [comment]
OK. Takk for informasjon. Får nå meldt på kandidater.

--
Thor Arne Johansen
