### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#34]
Vi forsøker å bruke RestSharp for å implementere et klientbibliotek.

Vi ser nå at ressurser returnerer forskjellige xml'er avhengig av suksess/feil.

Bl.a returnerer "/api/ekstern/kandidatpamelding" enten PameldingReference eller ApiError. Dette skaper ekstra kompleksitet  ettersom ved bruk av RestSharp gjøres kallet slik:
```C#
var response = client.Execute<T>(request);
```

Hvor T representerer returtypen. Dette skaper problemer ettersom .Execute kallet mottar to forskjellige xml'er avhengig av feilstatus, og klarer derfor ikke deserialisere korrekt. 

Det kan finnes måter å jobbe rundt dette uten at jeg vet helt hvordan ennå. Tenkte å høre først om det kan være aktuelt å returnere èn xml struktur pr. ressurskall og heller legge ApiError inne i xml strukturen (i steden for som som nå; en helt separat type).

--
Thor Arne Johansen
Oppad AS

**Comment by thoraj** [comment]
Jeg fikk ikke noe respons på min OP, så jeg måtte forsøke å implementere feilhåndtering som tar høyde for at type/struktur på returnert innhold kan variere (noe som kompliserer deserialisering/feilhåndteringen).

I forbindelse med testing av feilscenarier kan det se ut som jeg har oppdaget noe rusk/feil:
Det kan se ut som dokumentasjonen vedrørende returnering av feil ikke stemmer.

Vi forsøker å provosere frem feil ved å utføre kall som skulle føre til valideringsfeil i "/api/ekstern/kandidatpamelding" (ukorrekte eller manglende fødselsnummer, ukorrekt organisasjonskode, og feil eller manglende fagkode). Imidlertid returneres ingen feilkode, og i steden får vi en PameldingReference. 

I følge dokumentasjonen skal 400 og 500 feilmeldinger føre til at det returneres en ApiError. Vi opplever at vi noen ganger får returnert:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Error>
  <Message>An error has occurred.</Message>
</Error>
```

Er dette riktig? Skal vi forvente å få tilbake:
* Dokumentert xml struktur på 202/200?
* ApiError (ved hvilke HttpStatus koder)?
* Error (ved hvilke HttpStatus koder)

Gjøres validering i henhold til dokumentasjonen på testmiljøet i dag?

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Beklager litt sen respons på denne, men vi ser på en alternativ løsning for utfordringen du opplever. Når det gjelder feilkoder så skal du ikke få "An error has occured." så den skal jeg se nærmere på. Vi forsøker etter beste evne å alltid returnere ApiError dersom det oppstår noe feil.

For de andre tingene så har vi fått en del tilbakemeldinger på at vi har vært for strenge i valderingen på api/ekstern/kandidatpamelding så dette har vi gjort noen endringer på som kom ut i testmiljøet i dag. Dokumentasjonen er på vei til å oppdateres. Kort fortalt ønsker vi å akseptere påmeldingene så langt det lar seg gjøre, altså du vil få en referanse, for heller å kunne gi en bedre respons pr kandidat dersom noe feiler. F.eks at man forsøker en fagkode for en kandidat som ikke er gyldig etc.

**Comment by thoraj** [comment]
OK. Takk for svar. 

Ved å håndtere deserialisering selv (og ikke overlate det til RestSharp) samt introdusere en wrapper 
```c#
Pas2Wrapper<T> 
```
har jeg foreløpig jobbet rundt dette. Så det er ingen showstopper p.t. 

Men jeg kaster gladelig wrapper koden og overlater til RestSharp å deserialisere hvis dere gjør endringer her :-)

**Comment by aoksenholt** [comment]
Hvis det skal gjøres endringer mtp hva som returneres når, så håper jeg for all del at denne endringen blir bakoverkompatibel med slik det er i dag.
Siden retur er ulik avhengig http statuskode er det etter vår oppfatning helt greit å skille ulike responser.

**Comment by espenekvang** [comment]
Det blir ingen endring på dette foran våren 2016.
