### ISSUE TITLE
Påmelding med tom fagkode gir <Error> og ikke <ApiError>

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#37]
* Påmelding med tom fagkode gir ```<Error> og ikke <ApiError>```
* Påmelding med ugyldig organisasjonsnummer gir ```<Error> og ikke <ApiError>```

Er dette noe dere vil rette opp eller skal vi ta høyde for begge typer (Error og ApiError)

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Jeg ser nærmere på dette nå, gir deg tilbakemelding før lunsj i dag.

**Comment by espenekvang** [comment]
Da kan du forsøke igjen. Jeg har gjort justeringer nå og prøvd å sende inn påmeldingen du forsøkte å sende inn i går ca kl 1353. I den påmeldingen mangler du fødselsnummer for kandidaten. Feilmeldingen du skal få tilbake nå skal være av typen ApiError og den skal være beskrivende nok til at man skal skjønne hva og hvor (linjenummer) det faktisk er feil i XML man forsøker å sende inn.
