### ISSUE TITLE
Forskjell på behandling av nonce timestamp drift/test

### ISSUE THREAD

**Issue by WISove** [Utdanningsdirektoratet/PAS2-Public#39]
Må plusse på en time for å komme inn på drift i forhold til test.

**Comment by espenekvang** [comment]
Med drift mener du da https://eksamen.udir.no?

**Comment by WISove** [comment]
Ja

**Comment by espenekvang** [comment]
Beklager sen tilbakemelding på denne, jeg forstår at dere har dette problemet fremdeles og vi skal forsøke å hjelpe dere.

Aller først har dere implementert slik som beskrevet nederst i denne issue:

https://github.com/Utdanningsdirektoratet/PAS2-Public/issues/22

**Comment by espenekvang** [comment]
Denne informasjonen burde selvfølgelig vært dokumentert i Wiki'en under pålogging. Derfor har jeg lagt det inn der nå.

Igjen, beklager.

**Comment by espenekvang** [comment]
@WISove kan vi lukke denne saken?

**Comment by WISove** [comment]
Ja, nå får vi logget på igjen:)
