### ISSUE TITLE
Sertifikater

### ISSUE THREAD

**Issue by terje-barman** [Utdanningsdirektoratet/PAS2-Public#4]
Hei!

Vil det fremdeles være mulig å benytte vanlige sertifikater istedenfor virksomhetssertifikater i PAS2?

Vennlig hilsen
Terje Barman

**Comment by vidarkongsli** [comment]
Vi ønsker at det benyttes virksomhetssertifikater med mindre det er en god grunn til at virksomhetssertifikater ikke er tilgjengelig. Jeg vil for øvrig også si at et virksomhetssertifikat er å betrakte et “vanlig” sertifikat i de fleste henssender. Det eneste er at det setter en begrensning til hvem som er utsteder av sertifikatet (i praksis [Buypass](https://www.buypass.no/produkter-og-tjenester/virksomhetssertifikat) og [Commifes](https://www.commfides.com/e-ID/Bestill-Commfides-Virksomhetssertifikat.html)) og underlagt utsteders prosess for å opprette sertifikater.

For testing kan vi utstede testsertifikater som funksjonelt sett har de egenskaper vi er ute etter i et virksomhetssertifikat, slik at vi får til en troverdig test.

Les mer om virksomhetssertifikater [her](https://www.regjeringen.no/nb/dokument/dep/kmd/nouer/2001/nou-2001-10/16/3/id377594/)
