### ISSUE TITLE
Validering av epost-adresse

### ISSUE THREAD

**Issue by WISove** [Utdanningsdirektoratet/PAS2-Public#40]
Hvor nøye er deres side av epost-adressevalideringen?

Sjekker dere kun format, eller sjekker dere gyldig toppdomener også?

F.eks ove@wis.n  eller ove@wis.web som syntaksmessig er ok, men som ikke har gyldige toppdomener.

Ove B-)

**Comment by espenekvang** [comment]
Vi sjekker kun format.
