### ISSUE TITLE
Spesiell påmelding NOR0214, NOR0215 og NOR1415

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#41]
Den nye eksamenstjenesten legger noen spesielle krav på fagkodene NOR0214, NOR0215 og NOR1415.

En kandidat kan kun meldes på slik:
- enten i NOR1415. Da vil vi foreta sjekk på at påmeldingen ikke inneholder den aktuelle kandidatene i enten NOR0214 eller NOR0215, i tillegg sjekkes det at kandidaten ikke allerede er påmeldt i NOR0214 og NOR0215.
- eller i både NOR0214 og NOR0215 samtidig. Dette betyr at påmeldingen må inneholde kandidaten i begge disse fagkodene. Dersom det ikke gjøres vil det spesifiseres med en feilmelding når vi forsøker å foreta påmeldingen. Vi foretar også en sjekk på at kandidaten ikke allerede er påmeldt NOR1415.

**Comment by WISole** [comment]
Det betyr at man ikke kan melde opp ei gruppe med fagkode NOR0214, uten at man også legger med tilsvarende gruppe med kode NOR0215 i samme forsendelse?

**Comment by espenekvang** [comment]
Det stemmer.
