### ISSUE TITLE
Begrensinger i størrelsen på kandidatgrupper

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#42]
Finnes det noen begrensinger eller føringer på størrelsen på kandidatgrupper (antall kandidater)?

Det var såvidt jeg skjønner en begrensing på 30 kandidater tidligere, men får ingen feilmelding ved påmelding av en gruppe med 35 kandidater?

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Det er fremdeles slik at det i eksamenstjenesten kun vil være grupper på 30 kandidater. Når det er sagt kan du sende inn så store grupper du ønsker, tjenesten vil selv splitte og organisere dette i grupper på 30 internt.
