### ISSUE TITLE
Problemer med påmelding

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#43]
Jeg jobber med testing av eksamenspåmelding

Da jeg forsøker å melde på to kandidater i MAT0010 for V-2016 blir status for kandidatene "IkkePameldt", med begrunnelse "Påmeldingen er stengt."

Dette til tross for at påmeldingen skal være åpen til 30/12-2015 (ihht eksamensplan).

Er usikker på om jeg gjør noe feil eller om jeg har misforstått noe?

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Ok - jeg fikk en henvendelse på dette tidligere i dag også. Har nå forsøkt å justere klokkeslettene for påmeldingsfristen. Håper det blir bedre hvis ikke får jeg se nærmere på dette i ettermiddag.

**Comment by espenekvang** [comment]
Ble det bedre @thoraj?

**Comment by thoraj** [comment]
Ja, takk

Nå får jeg status "IkkeStartet", som sikkert skal indikere at kandidaten er påmeldt, men så langt ikke har møtt til eksamen.

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Nei, ikkestartet er ikke riktig. Du skal få Påmeldt status. Jeg er ikke i nærheten av en datamaskin nå, men kan se i kveld hva dette skyldes.
