### ISSUE TITLE
Henting av påmeldte

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#44]
Vi tester påmelding av kandidater. 

Vi har fått meldt på to kandidater til MAT0010 for V-2016 perioden. Vi har verifisert påmeldingen vha ressursen "~/api/ekstern/kandidatpamelding/{guid}"

Når vi forsøker å hente kandidatoversikt via ressursen  "~/api/ekstern/kandidat?orgno={orgno}&periodekode={periodekode}"

får vi en tom xml struktur
```xml
<?xml version="1.0" encoding="utf-8"?>
<pa:PameldteKandidater xmlns:ct="http://pas.udir.no/CommonTypes" xmlns:ko="http://pas.udir.no/Karakteroversikt" xmlns:ep="http://pas.udir.no/Eksamensplan" xmlns:pa="http://pas.udir.no/Pamelding">
  <pa:Eksamensperiodekode>V-2016</pa:Eksamensperiodekode>
  <pa:Eksamenspameldinger />
</pa:PameldteKandidater>
```

Denne lar seg ikke deserialisere til "PameldteKandidater" typen på samme vis som øvrig returnert xml. Dette kan imidlertid ha andre årsaker. 

Så spørsmålet er egentlig:   Burde ikke ressursen "~/api/ekstern/kandidat?orgno={orgno}&periodekode={periodekode}" returnere alle påmeldte kandidater for det spesifiserte orgnummeret og eksamensperioden?

--
Thor Arne Johansen
Oppad AS

:

**Comment by thomashannestad** [comment]
Påmeldingsstatusen du beskrev i forrige epost «Ikke startet» betyr at påmeldingen ligger i kø og ikke er gjennomført. Trolig derfor du ikke får noen kandidater tilbake.


Med vennlig hilsen
Thomas Hannestad
Barman Hanssen AS
thomas@barman-hanssen.no

**Comment by espenekvang** [comment]
Det er riktig som det påpekes her. Du skal få tilbake påmeldte. Jeg skal undersøke dette i kveld

**Comment by thoraj** [comment]
Ok.

Takk for svar 

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Det var en feil relatert til å hente ut kandidater. 
Feilen er fikset og ny versjon er lagt ut i testmiljøet (https://eksamen-sas.udir.no).

**Comment by thoraj** [comment]
Har hatt disk/OS havari, og ikke fått sjekket dette før nå. 

Returnert xml struktur ser mye mer fornuftig ut nå. Sliter fortsatt med deserialisering, men dette har sannsynligvis andre årsaker.

--
Thor Arne
