### ISSUE TITLE
Påmelding, endringer

### ISSUE THREAD

**Issue by WISole** [Utdanningsdirektoratet/PAS2-Public#45]
Jeg prøver ut litt ulike scenarioer for påmeldinger, opplasting av endringer.
-  endring av gruppenavn i SAS: oppdaterer ikke PAS

- fjerner elev fra gruppe i SAS: oppdaterer ikke PAS

- flytting av elever fra en gruppe til annen gruppe (med annen fagkode) i SAS: PAS beholder eleven i gammel gruppe, og oppretter i tillegg kandidaten inn i den nye gruppen

- flytting av elever fra en gruppe til annen gruppe (med samme fagkode) i SAS: PAS beholder eleven i gammel gruppe. Eleven blir ikke lagt inn i ny gruppe.

Det betyr at etter at påmelding er gjort første gang så er disse gruppene på en måte satt. Nye grupper med nye kandidater kan opprettes. Flytting av kandidater mellom grupper må eventuelt skje ved å fjerne kandidaten fra den gamle gruppa i PAS og overføre data på nytt. Sletting av kandidat må gjøres i PAS.

Det stemmer at det er sånn det vil fungere?

**Comment by espenekvang** [comment]
Ja, det stemmer. Vi har foreløpig ikke støtte for sletting/flytting av elever.
