### ISSUE TITLE
Opplæringsnivå i påmeldingsrapport

### ISSUE THREAD

**Issue by aoksenholt** [Utdanningsdirektoratet/PAS2-Public#46]
Hei

Implementasjonen vi har i produksjon pdd baserer seg på et skjema hvor PameldingReport.Opplaeringsniva finnes. Skjema som ble lastet ned i dag inneholder ikke dette feltet lengre, noe som skaper problemer.

Usikkert for oss når dette forsvant, men siden dette er noe vi er avhengig av er det meget ønskelig at det kan gjeninnføres så snart som mulig.

**Comment by espenekvang** [comment]
Dette er omtalt i issue #35, men i korte trekk var det nødvendig å flytte opplæringsnivået ned til kandidatgruppe for å kunne støtte påmelding til skoler med flere opplæringsnivåer.

**Comment by aoksenholt** [comment]
Ok, takk.

**Comment by aoksenholt** [comment]
Dette kan ha blitt omtalt tidligere, men..

På påmeldinger/kandidater som får status "IkkePåmeldt" så kommer ikke Opplæringsnivå med.
Er dette bevisst eller en feil/mangel?

```XML
        <Kandidatgruppe>
            <Navn>VAFPRIV-E-E131-HST3003-1</Navn>
            <Fagkode>HST3003</Fagkode>
            <Variant></Variant>
            <Kandidatgruppeansvarlige/>
            <Kandidater>
                <Kandidat>
                    <Fodselsnr>xxxx</Fodselsnr>
                    <Status>IkkePameldt</Status>
                    <StatusMessage>Fagkoden HST3003 er ikke kjent i eksamensperioden du forsÃ¸ker Ã¥ melde pÃ¥.</StatusMessage>
                </Kandidat>
            </Kandidater>
        </Kandidatgruppe>
```

**Comment by espenekvang** [comment]
Vi henter ut opplæringsnivå fra fagkoden. Siden fagkoden i dette tilfellet ikke er kjent for oss så klarer vi heller ikke å hente ut opplæringsnivå. Ved første øyekast kan man da tenke seg at vi bør hente opplæringsnivå fra skolen, men siden skoler kan ha flere opplæringsnivå og en påmelding kan inneholde påmeldinger til flere opplæringsnivå blir det vanskelig.

Skaper det store problemer for dere?

**Comment by aoksenholt** [comment]
Det skaper problemer slik vi har det nå, men må se på en alternativ løsning.

**Comment by espenekvang** [comment]
Er det en mulighet å bare tillate å sende inn fagkoder som dere finner på eksamensplanen vi leverer ut på api/ekstern/eksamensplan? eller er det slik at brukerne kan velge fritt mellom alle mulige fagkoder?

**Comment by aoksenholt** [comment]
Ideelt sett bør det bare sendes opp på koder som finnes i eksamensplanen, men det blir ikke alltid slik..
Vi gjør en workaround for å få det til å fungere slik det er i dag.
