### ISSUE TITLE
Feil i fødselsnummervalidering?

### ISSUE THREAD

**Issue by aoksenholt** [Utdanningsdirektoratet/PAS2-Public#48]
Vi forsøker å melde opp kandidater, men får IKKE_PAMLEDT med melding

"Fødselsnummeret er ikke gyldig. Du må bruke kandidatens riktige fødselsnummer, D-nummer eller DUF-nummer. Hvis kandidaten ikke har et slikt nummer, kan du generere et fiktivt fødselsnummer i eksamenstjenesten, men da må du gjøre påmeldingen direkte i eksamenstjenesten. Fiktive fødselsnumre generert andre stedet enn i eksamenstjenesten skal IKKE brukes."

selv om vi sender med noen reelle fødselsnummer (ansatte hos oss).

Påmeldingsreferanse: d33fb98e-5eb9-4cf8-b5b1-1a66b089c3c7

**Comment by espenekvang** [comment]
Feilmeldingen var feil i dette tilfellet. Det er fødselsnummeret på kandidatgruppeansvarlig som ikke er riktig. Vi har korrigert feilmeldingen nå slik at du bør se en riktigere feilmelding for dette i testmiljøet. Forventer at denne endringer blir produksjonssatt i løpet av kvelden i morgen

**Comment by aoksenholt** [comment]
Ok.
Får http 500 på kandidatpåmelding-API'et i dag (samme tester som i går).

**Comment by espenekvang** [comment]
Siden dere har identifisert feilen, lukker jeg denne.
