### ISSUE TITLE
Håndtering av Kandidatgruppeansvarlig

### ISSUE THREAD

**Issue by Sveinj** [Utdanningsdirektoratet/PAS2-Public#49]
Hvordan håndtereres feltet Kandidatgruppeansvarlig ift oppdateringer/endringer ved flere opplastinger?

**Comment by espenekvang** [comment]
Eventuelle tillegg vil bli oppdatert, men sletting av kandidatgruppeansvarlig vil man måtte gjøre i selve eksamenstjenesten.
