### ISSUE TITLE
Hvor får jeg tak i validerings skjemaene ?

### ISSUE THREAD

**Issue by Thor-Kristian-Valderhaug** [Utdanningsdirektoratet/PAS2-Public#5]
Hvor får jeg tak i xsd skjemaene som brukes for å validere forespørsler  som gjøres mot APIet ?

**Comment by Thor-Kristian-Valderhaug** [comment]
En zip fil med alle skjemaene som brukes av APIet kna lastes ned fra http://eksamen-tst2.udir.no/api/ekstern/skjemaer

**Comment by aoksenholt** [comment]
zip-fil finnes (foreløpig?) ikke på den nevnte url'en.

**Comment by Thor-Kristian-Valderhaug** [comment]
Den bør være tilgjengelig i løpet av dagen

**Comment by Thor-Kristian-Valderhaug** [comment]
Da skal zip være tilgjengelig. Url i den første kommentaren var feil (har rettet opp nå) riktig url er https://eksamen-tst2.udir.no/api/ekstern/skjemaer

**Comment by espenekvang** [comment]
Det er satt opp eget testmiljø for SAS'ene så riktig url her er nå: https://eksamen-sas.udir.no/api/ekstern/skjema
