### ISSUE TITLE
Eksamen grunnskole for voksne

### ISSUE THREAD

**Issue by AMNytroen** [Utdanningsdirektoratet/PAS2-Public#51]
Hvordan er det tenkt å melde på elever i Voksenopplæringa som skal ta eksamen grunnskole? skal de meldes opp til samme eksamen som øvrige avgangselever eller er det noe spesielt å ta hensyn til?

**Comment by espenekvang** [comment]
De skal meldes opp som øvrige avgangselever på den voksenopplæringen de er elever ved. Vi håper å få på plass voksenopplæringssenteret i løsningen i løpet av denne uken

**Comment by AMNytroen** [comment]
ingen spesielle prøvetyper?

**Comment by espenekvang** [comment]
Nei, det er ingen spesielle fagkoder for eksamen når det gjelder voksenopplæring.
