### ISSUE TITLE
Oppmelding av flere en en kandidatgruppe per fagkode

### ISSUE THREAD

**Issue by AMNytroen** [Utdanningsdirektoratet/PAS2-Public#53]
Hei
Vi har forsøkt å melde opp flere grupper i samme fagkode, men med noe ulike kandidatgruppenavn i Oppad:PAS_ENG0010 _1, PAS_ENG0010_2 osv.
Når vi overfører til "PAS2" viser det seg at alle elevene som ble oppmeldt i ENG0010 legges i samme kandidatgruppe og kandidatgruppenavnet er ENG0010, det samme som fagkoden de er oppmeldt i. Hva er det vi har gjort feil da?

**Comment by thoraj** [comment]
Skolene deler ofte eksamenspartiene opp i grupper i henhold til tilgjengelige rom/romkapasitet etc. 

Men basert på dette Anne Mari nevner og tidligere kommunisert info her ser det ut som:

* PAS kan velge å dele opp påmeldte kandidatgrupperi mindre grupper
 * Hva skjer med kandidatgruppenavn da?
* PAS kan velge å slå sammen påmeldte grupper i en større (samle)gruppe for fagkoden
 * Hva skjer med kandidatgruppenavn da?

Har det i så fall noe mening at vi bruker kandidatgruppenavn ved påmelding? Slik vi forstår dette vil disse navnene ikke gjenfinnes i det sentrale PAS web grensesnittet, og de vil heller ikke opptre i svar vi får fra PAS på f.eks kall mot ressursen **"/api/kandidat"**

--
Thor Arne Johansen
Oppad AS

**Comment by espenekvang** [comment]
Så vidt jeg kan se forsøker dere å gjøre dette i testmiljøet?
Det er feil at kandidatene legges i samme gruppe med navnet ENG0010 - dette ser vi nærmere på nå.

Reglene er slik:
- det originale kandidatgruppenavnet fra et SAS skal beholdes så lenge gruppen i PAS inneholder inntil 30 kandidater
- dersom gruppen overstiger 30 kandidater vil man opprette en ny gruppe med samme navn som den originale, med med et internt suffix i PAS.

Navnet på kandidatgruppene som dere sender inn vil være synlig for brukerne av PAS når de logger inn i påmeldingsoversikten på sin skole.

**Comment by espenekvang** [comment]
Vi har foretatt litt undersøker basert på situasjonen dere har beskrevet over. Vi ser at dere har initelt sendt inn påmelding på kandidater 12 januar og da har dere spesifisert at kandidaten skal ta eksamen i ENG0012 med tilhørende kandidatgruppe ENG0012. Påmeldingen av kandidatene ble da fullført.

På et senere tidspunkt (26. januar) har dere sendt inn de samme kandidatene, på den samme fagkoden, men denne gangen i en annen kandidatgruppe. Da vil kandidatene allerede være påmeldt i den aktuelle fagkoden og kandidatnummere de fikk første gangen vil være det dere får tilbake. Flytting av en kandidat fra en kandidatgruppe til en annen er ikke støttet.

**Comment by aoksenholt** [comment]
Det er greit, men kan ikke opplæringsnivå sendes med i slike tilfeller også?

**Comment by espenekvang** [comment]
@aoksenholt hva mener du?

**Comment by aoksenholt** [comment]
Beklager, gikk litt fort og ble kommentar på feil sak.. Slettet!
