### ISSUE TITLE
Innloggingsløsning

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#54]
Vi vurderer mulige innloggingsløsninger for apier mot Oppad fagsystemer. 

Har dere mulighet for å dele noe informasjon/kode/skisser/produktnavn etc som viser hvordan dette ble gjort nå i rest apiet for den nye eksamenspåmeldingen.

Thor Arne Johansen 
Oppad AS

**Comment by espenekvang** [comment]
Beklager seint svar på denne.

For å logge på i API'et må man som kjent POST'e inn en XML på en gitt struktur. Ved mottak av denne XML'en gjennomfører vi validering av strukturen mot XSD. I korte trekk gjør vi følgende:

- validere struktur i XML mot XSD
- verifisere signature i XML ved bruk av ```SignedXml``` (```CheckSignature()```)
- verifiserer trust av sertifikat
- verifisere nonce for å sikre at det ikke er replay attempt
- dersom alle overnevnte steg er vellykket opprettes en ```ClaimsPrincipal``` med det settet av ```Claims``` som er nødvendig for den gitte brukeren.
- ```ClaimsPrincipal``` skrives til Cookie ved hjelp av ```FederatedAuthentication.SessionAuthenticationModule```

Siden vi benytter standard .NET authentiseringsmekanisme kan vi benytte ```[Authorize]```-attributtet på våre kontrollere for å sikre rett tilgang.

**Comment by thoraj** [comment]
Takk for svar og beskrivelse

Så dere bruker ikke ThinkTecture.IdentityServer eller andre produkter?

Våre løsninger benytter også Claims basert (føderert) autentisering og det hadde vært snedig å kunne benytte vår eksisterende måte for autorisering på også for vårt offentlige API. Dette forutsetter at api klienten presenterer en FedAuth cookie noe som jo skjer i Pas2/Eksamen.

Derfor lurer vi på om koden i sin helhet eller utdrag av de delene som verifiserer sertifikat og utsteder cookie er tilgjengelig på noe vis? Selv klipp og lim av kontrollerkoden i en epost vil være nyttig.

Jeg har full forståelse for at dere ikke kan drive support på denne koden/løsningen ovenfor leverandører, og forventer heller ikke det. Men det hadde spart oss en del tid å ha kode å kikke på hvis vi velger samme rute (lage egen autentisering fremfor å tilpasse f.eks identityserver).

mvh,
Thor Arne Johansen

**Comment by espenekvang** [comment]
Vi benytter ThinkTecture.IdentityServer i påloggingsløsningen for hovedapplikasjonen vår. I tillegg har vi nå startet arbeidet med å skille ut API'et slik at det også vil få ny pålogging som benytter bearertoken ved hjelp av ThinkTecture.IdentityServer.

Jeg skal undersøke om jeg kan sende deg kode for løsningen slik den er i dag.
