### ISSUE TITLE
Testeksamen

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#55]
I løpet av april vil det gjennomføres en testeksamen i produksjonssystemet der skolene kan velge å gjennomføre et testarrangement for å sikre at skolen er riktig koblet opp mot PAS.

I den forbindelse vil det legges til noen nye fiktive fagkoder i eksamensplanen som blir tilgjengeliggjort gjennom integrasjonen slik at skoleadministratorer skal få mulighet til å melde på kandidater også på disse fagkodene.

Det er derfor viktig at bruker av det skoleadministrative systemet vil få mulighet til å melde opp et sett med kandidater i de nye fagkodene når de blir tilgjengelige.

Er det noen som ser noen utfordringer med dette?

**Comment by terje-barman** [comment]
Hei!

Bare vi på forhånd får fagkodene og informasjon om det er andre avvik i forbindelse med de fiktive partiene. Jeg antar de blir slettet etter testen er gjennomført?

Vennlig hilsen
Terje Barman
------------------------
Barman Hanssen AS

**Comment by espenekvang** [comment]
Det skal dere få informasjon om. Partiene vil bli ryddet opp etter gjennomføring.

**Comment by AMNytroen** [comment]
Skal "prøveperioden" settes til  V-2016 for vår 2016 og opplaeringsniva være GS for grunnskole som for eksamen eller er det egen perioode for denne testen?

**Comment by espenekvang** [comment]
Det er ingen egen prøveperiode for dette. Vi benytter V-2016

**Comment by AMNytroen** [comment]
Vi kan ikke se at den er åpen for integrasjonen. Stemmer det?
Vårt oppslag i «gamle oppad» gir kun disse fagkodene:
[cid:image001.png@01D18E58.1CEE4AA0]

Mvh
Anne Mari
Oppad Support


Fra: Espen Ekvang [mailto:notifications@github.com]
Sendt: 4. april 2016 09:50
Til: Utdanningsdirektoratet/PAS2-Public <PAS2-Public@noreply.github.com>
Kopi: Anne Mari Nytrøen <annytr@oppad.no>
Emne: Re: [Utdanningsdirektoratet/PAS2-Public] Testeksamen (#55)


Det er ingen egen prøveperiode for dette. Vi benytter V-2016

**Comment by espenekvang** [comment]
TST fagkodene mangler i testmiljøet (https://eksamen-sas.udir.no), men er lagt inn i produksjonsmiljøet.

Får dere ikke opp TST-kodene i produksjonsmiljøet:

https://eksamen.udir.no/api/ekstern/eksamensplan

Vi jobber med å få lagt inn TST-kodene i testmiljøet også nå.

**Comment by espenekvang** [comment]
Da er TST-kodene på plass i testmiljøet også (https://eksamen-sas.udir.no).
Si ifra hvis dere fremdeles ikke får tak i disse.
