### ISSUE TITLE
Ende-til-ende test

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#56]
Vi planlegger en ende-til-ende test og ser på muligheten for å la dere teste mot et annet testmiljø enn det som er dedikert SAS'ene.

Hvor stor jobb er det for dere å endre endepunktet dere går mot i test?
Er det bare en konfigurasjonsendring?

**Comment by espenekvang** [comment]
Dette gjelder spesielt tilbakeføring av karakter for grunnskole for de som ønsker å teste dette.

**Comment by aoksenholt** [comment]
Helt i orden for oss (IST) å endre på test-endpoint.

**Comment by thoraj** [comment]
Konfigurasjonsendring her også såfremt vi kan bruke samme sertifikat

--
Thor Arne
(Oppad)

2016-03-18 11:56 GMT+01:00 Anders B. Øksenholt <notifications@github.com>:
