### ISSUE TITLE
test for å hente ut karakteroversikt

### ISSUE THREAD

**Issue by AMNytroen** [Utdanningsdirektoratet/PAS2-Public#57]
Vi ønsker å teste dette og lurer på hvordan vi forholder oss til dette rent praktisk.

1. Vil karakteroversikten bestå av reelle data, så vi må avtale med en skole som er i produksjon, eller er det på fiktive data? 
2. Hvis det siste, hva må være på plass på vår side før vi kan teste? Jeg tenker da på opplysninger som enhet, grupper, fagkoder og elevdata.
3. Eller er det slik at testen foregår begge veier: at vi både skal melde opp noe til testbasen og så få karakterdata tilbake? Kreves det bestemte data på enhet og fagkoder?

**Comment by espenekvang** [comment]
1. Det vil være fiktive data. Dere kan selv velge en skole og en fagkode og foreta påmelding på denne i testmiljøet. Vi vil så gjennomføre sensur slik at dere kan hente ut karakteroversikten.
2. Dere velger som sagt skole, fagkode, elever, grupper etc.
