### ISSUE TITLE
Varianter av fagkoder

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#58]
Vi holder på å kartlegge kravene for lokalgitt eksamen med varianter som skal implementeres i PAS og være klar til bruk fra høsten.

I dagens løsning er det kun støtte for varianter for REA3015, men fra høsten vil dette kunne konfigureres i PAS og hvilke fagkoder som har varianter vil variere mellom fylker og skoler. Mesteparten av endringene for å støtte dette vil skje internt i PAS og dere som skoleadministrative systemer vil ikke behøve å justere dere så veldig mye. Når det er sagt trenger vi en bekreftelse på følgende:

I dag er det slik at feltet varianter er garantert en maksimal lengde på 3 tegn. Fra høsten vil dette feltet bli større og foreløpig er det identifisert at det må hvertfall være 4 tegn. Spørsmålet til dere er derfor:  
- **Hva er konsekvensen for dere å øke lengden på dette feltet?** 
- **Vil det være gjennomførbart å øke denne lengden slik at det er klart til høsten?**

Dette dreier seg altså om feltet _Variant_ under noden _Eksamen_ på data som vi leverer ut fra ~/api/ekstern/eksamensplan og feltet _Variant_ på noden _Kandidatgruppe_ som dere kan oppgi som en del av påmeldingen dere sender inn på ~/api/ekstern/kandidatpamelding.

@AMNytroen @aoksenholt @thoraj @WISole @mhjelmseth @asands @thomashannestad @terje-barman

**Comment by thomashannestad** [comment]
Økt lengde har ingen konsekvenser for oss. For inntil 10 tegn er vi klare fra i dag.

Med vennlig hilsen
Thomas Hannestad
Barman Hanssen AS
thomas@barman-hanssen.no

**Comment by sonjagrydeland** [comment]
For Extens sin del (IST) kan jeg  ikke svare før vi har fått tilbakemelding fra progr.avdeling i Växjo - da dette blir en helt ny omlegging og bruk av feltet i forhold til hva dere skisserte ved REA3015. Jeg må sjekke om en kan legge over feltet til å kommunisere med PAS (som prøveperiode, prøvetype - via hente prøvedata) - slik er det ikke i dag, siden bestillingen først var noe annet ved variant. I tillegg sjekke om vi i databasen kan øke antall tegn fra 3 og til slutt når dette kan leveres. Deretter må det endres oppsettet mht integrasjonen - og det er det A.Øksenholt som kan svare på.

Mvh
Sonja Grydeland, prod.ansvarlig Extens

**Comment by mhjelmseth** [comment]
Dette får ingen konsekvenser for Visma FLYT Skole.

mvh
Morten Hjelmseth
Senior Software Developer
Visma Software Labs AS

**Comment by WISole** [comment]
Endringer i feltstørrelse på varianter har ingen konsekvenser for Wis skole

**Comment by Sveinj** [comment]
Endringer i feltlengde inntil 10 tegn er helt ok for IST sine tre systemer: Extens, SATS og IST Skoleadministrasjon (hypernet)
