### ISSUE TITLE
Hva brukes Competence til i domenemodellen for prøvedefinisjoner?

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#6]
Vi jobber med å se på domenemodellen ut mot SAS'ene og har startet med funksjonaliteten for å hente ut prøvedefinisjoner. I dagens integrasjon mot PAS heter funksjonen ExportTestDefinitionsFromPas og befinner seg i tjenesten SASTestDefinitionsService.svc. I modellen som returneres som respons på denne tjenesten får man en struktur som blant annet returnerer et Competence-objekt.

Spørsmål:
1. Hva brukes denne informasjonen til av SAS'ene?
2. Er den relevant for både eksamen og prøver?

@aoksenholt

**Comment by aoksenholt** [comment]
> 1. Hva brukes denne informasjonen til av SAS'ene?

Oppslag/referanse.

> 2. Er den relevant for både eksamen og prøver?

Mest relevant for prøver (GRS) (pga "ustandard" gyldige resultater)

**Comment by espenekvang** [comment]
Ok - da kan vi utelatte dette Competence siden vi nå i første omgang konsentrerer oss om eksamen?

**Comment by aoksenholt** [comment]
Ja. Dette betyr altså at det blir helt nye skjemaer for payload også, ikke bare grensesnittet mot PAS som endres.

**Comment by espenekvang** [comment]
Det stemmer. Vi ønsker at payloaden skal gjenspeile domenemodellen vi jobber med og at det skal være tydelig skille på eksamen og prøver.
