### ISSUE TITLE
Grensesnitt for prøver - prøveoversikt

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#65]
Vi har første utkast til modellen for prøveoversikt klar nå. Vi ønsker tilbakemelding fra dere om det er informasjon dere mangler fra det gamle. Kort sagt har vi slanket denne en god del fra det som var tilgjengelig i det gamle grensesnittet for PAS1. Den gamle tjenesten heter `ExportTestDefinitionsFromPAS` og som dere vil se er følgende elementer ikke lenger en del av kontrakten:
- `TestPeriod` periode for prøver utgår, vi ønsker at man skal få ut de prøvene som er tilgjengelige for påmelding når man spør tjenesten
- `Competence` her trenger vi innspill fra dere. Er dette noe som brukes i dag? Og i tilfelle ja, hva er behovet her?
- ~~`SubjectCode` er også tatt bort. Dette for å gjøre det mer tydelig hva slags prøve det er. De nye feltene type, trinn, variant og ferdighet skal tilsammen være tilstrekkelig informasjon for å kunne fortelle hvilken prøve det er. Er det noen som har behov for å få den gamle prøvekoden?~~

Illustrasjon av utkastet til modellen finner dere her: https://goo.gl/CtFYgI

cc @aoksenholt @terje-barman @Sveinj @thomashannestad @thoraj @WISove

**Comment by espenekvang** [comment]
Første utgave av API'et for denne ressursen er nå tilgjengeliggjort i testmiljøet. Det er foreløpig ikke reelle data, men endepunktet er der og vil returnere noe som representerer strukturen som er nevnt over. 

URL: https://proverapi-sas.udir.no/sas/proveoversikt
XSD: https://proverapi-sas.udir.no/sas/schema

**Comment by espenekvang** [comment]
Prøveoversikten er nå oppdatert og inneholder den informasjonen vi forventer at vi skal måtte levere ut til skoleadministrative systemer. Endringen nå er at man _må_ oppgi organisasjonsnummer til skolen man ønsker å hente en prøveoversikt for. Bakgrunnen for dette er at dere vil kun få ut prøver som er gyldige på den skolen dere spør for. Gyldigheten valideres opp mot hvilke skoletrinn som er tilgjengelig på skolen. Vi har oppdatert testmiljøet med den digitale kartlegginsprøven som skal være nå i høst. I tillegg er det et sett med Prøvebankprøver som skolene også skal kunne melde på til.

Dere vil også se at `Kode` er lagt til per prøve som er prøvekoden for en gitt prøve. Det er nødvendig for å sikre bakoverkompabilitet spesielt for prøvebankprøvene at vi benytter prøvekoden.

**Comment by espenekvang** [comment]
Hvor mange tegn kan dere lagre i feltet for koden som benyttes for en prøve? I prøveoversikten som dere kan hente ut fra ~sas/proveoversikt er det som sagt et felt som heter `Kode`. Det er **veldig** viktig at vi får kartlagt om det er begresninger i dette feltet.

Jeg gjentar spørsmålet: hvor mange tegn forventer dere at dere kan håndtere i feltet `Kode` som kommer på en prøve. Denne koden skal også benyttes ved påmelding til en prøve.

@aoksenholt @terje-barman @Sveinj @thomashannestad @thoraj @WISove

**Comment by terje-barman** [comment]
Hei!

 

Vi kan lagre 8 tegn i kode-feltet, men vi kan utvide det om det skulle komme lengre fagkoder. Hva er bakgrunnen for spørsmålet? Vi ønsker svært gjerne å unngå logikk i fagkodefeltet.

 

Vennlig hilsen

Terje Barman

-------------------------------------------------

Barman Hanssen AS

Epost: terje@barman-hanssen.no

Mob.: 0047 993 98 715

Skype: terje.barman

 

Fra: Espen Ekvang <notifications@github.com>
Svar til: Utdanningsdirektoratet/PAS2-Public <reply@reply.github.com>
Dato: mandag 3. oktober 2016 13.55
Til: Utdanningsdirektoratet/PAS2-Public <PAS2-Public@noreply.github.com>
Kopi: terje-barman <terje@barman-hanssen.no>, Mention <mention@noreply.github.com>
Emne: Re: [Utdanningsdirektoratet/PAS2-Public] Grensesnitt for prøver - prøveoversikt (#65)

 

Hvor mange tegn kan dere lagre i feltet for koden som benyttes for en prøve? I prøveoversikten som dere kan hente ut fra ~sas/proveoversikt er det som sagt et felt som heter Kode. Det er veldig viktig at vi får kartlagt om det er begresninger i dette feltet.

Jeg gjentar spørsmålet: hvor mange tegn forventer dere at dere kan håndtere i feltet Kode som kommer på en prøve. Denne koden skal også benyttes ved påmelding til en prøve.

@aoksenholt @terje-barman @Sveinj @thomashannestad @thoraj @WISove

**Comment by espenekvang** [comment]
Det er ingen logikk i kodefeltet. Bakgrunnen for spørsmålet er at vi må supportere gamle prøvebankkoder og disse kan være ganske lange (se eksempler fra testmiljøet: https://proverapi-tst2.udir.no/sas/proveoversikt?skoleorgno=874568082). Dersom det er begrensninger hos mange leverandører må vi revurdere hvordan vi skal kunne motta påmeldinger til en gitt prøvebankprøve.

**Comment by espenekvang** [comment]
Det har kommet spørsmål om informasjon om variant etc på en gitt prøve. Det er foreløpig ikke tilgjengelig funksjonalitet i prøvetjenesten at man skal kunne håndtere varianter som kommer mer mtp nasjonale prøver og pilotering. Når det er sagt er det definert hvordan ekstra informasjon skal kunne ligge på prøven. Vi har nå utvidet prøveoversikten til å kunne inneholde denne ekstra informasjonen. Dette er rullet ut i alle miljøer. Oppdatert dokumentasjon finner dere på WIKI og her er lenke til modellen: https://www.lucidchart.com/publicSegments/view/f1c5987e-021d-4e26-9dd5-6cfffebc65b7/image.png
