### ISSUE TITLE
Grensesnitt for prøver - påmelding

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#66]
Vi har første utkast til modellen for påmelding av elever klar nå. Vi ønsker tilbakemelding fra dere om det er informasjon dere mangler fra det gamle. Den gamle tjenesten heter `ImportStudentsToPAS`. Flere elementer av den gamle kontrakten er ikke lenger med fordi vi på nåværende tidspunkt ikke ser behov for disse. Påmeldingsmodellen er nå basert på det vi har for den nye eksamenstjenesten, men er rettet mot prøver domenet. Vi ønsker input fra dere både på modellen for å sende inn en påmelding og modellen som er foreslått for rapporten som dere vil kunne hente ut. Som sagt i møtet denne uken vil vi ha samme konsept som for eksamen der man sender inn en påmelding og mottar en referansen til påmeldingen hvor man på et senere tidspunkt kan etterspørre status og motta en påmeldingsrapport.

Modell for påmelding av elever: https://goo.gl/zvsVit
Modell for påmeldingsrapport: https://goo.gl/w4MFZ3

cc @aoksenholt @terje-barman @Sveinj @thomashannestad @thoraj @WISove

**Comment by WISole** [comment]
Provegruppe i påmeldingsmodellen må vel ha Type? I tillegg til trinn, variant og ferdighet?

**Comment by espenekvang** [comment]
Det er helt riktig @WISole. Diagrammet er oppdatert.

**Comment by espenekvang** [comment]
Kontrakten for å foreta påmelding og hente ut rapport er nå tilgjengelig i testmiljøet https://proverapi-sas.udir.no. Foreløpig vil endepunktet akseptere data og ikke gjøre noe med det og rapporten man får ut er statisk og lik for alle, men det skal være nok til at dere kan begynne å se på hvilke data dere må sende inn og hvilke data dere kan forvente å få ut.

Påmelding gjøres nesten som i eksamen ved å gjøre en POST til ~/sas/pamelding der payloaden er XML. Som respons fra denne ressursen vil man få en referanse (guid) som man igjen kan benytte for å hente ut status fra ~/sas/pamelding/{guid}. Så konseptet fra eksamen er videreført.

Wikien her på siden er oppdatert med beskrivelse av endepunktene med lenker til illustrasjon av datamodellene.
