### ISSUE TITLE
Nye properties i TestPeriod

### ISSUE THREAD

**Issue by aoksenholt** [Utdanningsdirektoratet/PAS2-Public#7]
*ExportTestdefinitionsFromPASResponse* inneholder i dag perioder med en start- og sluttdato. Disse datoene representerer ikke selve gjennomføringsperioden for eksamen/prøver, men den "adminstrative" perioden (når PAS er åpen for administrasjon av prøver i den gitte periode).

```XML
    <b:TestType>
		<b:TestTypeCode>EG</b:TestTypeCode>
		<b:TestTypeName>Eksamen grunnskole</b:TestTypeName>
		<b:TestPeriods>
			<b:TestPeriod>
				<b:TestPeriodCode>V-2015</b:TestPeriodCode>
				<b:StartDate>2014-10-30T00:00:00</b:StartDate>
				<b:EndDate>2015-08-31T00:00:00</b:EndDate>
```			

Det er ønskelig at perioder utvides med start-/sluttdato for selve gjennomføringen av eksamen/prøver i perioden (f.eks for EG V-2015: start:2015-05-18 end:2015-05-27)

**Comment by espenekvang** [comment]
Trenger dere både de administrative datoene, eller er det nok med Gjennomføringsdatoene?

**Comment by aoksenholt** [comment]
Nei, vi har ingen behov for annet enn gjennomføringsdatoer.

**Comment by espenekvang** [comment]
Vi har lagt ut første utkast til den nye versjonen av _ExportTestDefinitionsFromPAS_. Vi opererer nå med en struktur som heter _EksamensPlan_ og det vil være en eksamensplan for hvert opplæringsnivå (grunnskole, videregående). Det er ikke reelle data som returneres foreløpig, kun data for å vise strukturen i sin enkleste form.

Eksamensplan får man ved å gjøre følgende:
GET https://eksamen-tst2.udir.no/api/ekstern/eksamensplaner

Domenemodellen som returneres er illustrert [her] (https://www.lucidchart.com/publicSegments/view/54de06af-21dc-4551-bf45-15a50a005a92/image.png).

Kan dere se om det er noen åpenbare mangler i det som returneres? @aoksenholt

**Comment by espenekvang** [comment]
Ressurser og hvilke verb som støttes blir fortløpende beskrevet under seksjonen for SAS integrasjon på WIKI'en som finnes [her] (https://github.com/Utdanningsdirektoratet/PAS2-Public/wiki/03.-SAS-Integrasjon)

**Comment by aoksenholt** [comment]
**EksamensPeriode**

* Mangler datoer for selve gjennomføringen.

**Eksamen.Eksamensdeler.Eksamensdel**

* Ønskelig med typifisering av EksamensdelType (altså ikke fritekst). F.eks referanse til Grep sin eksamensform-paa-vitnemaalet eller andre gitte koder (XSD restriction ?).
* Info om eksamensdel er forberedelse eller hoveddel

**Comment by espenekvang** [comment]
Takk skal du ha.

**EksamensPeriode**
- Dato for gjennomføringen vil ligge på eksamensdelen, vi endrer navnene til å være prefikset med _Gjennomføring_ i stedet for Tidspunkt for at det skal bli klarere

**Eksamen.Eksamensdeler.Eksamensdel**
- EksamensdelType er definert i PAS og Grep har ingen kjennskap til disse verdiene. Det er pr nå fire mulige verdier (Eksamen, Eksamen Del 1, Eksamen Del 2 og Forberedelse). Verdiene vil være faste og det er fullt mulig å legge inn XSD restriction i forhold til det.
- Hva benytter dere informasjon om forberedelse eller hoveddel til? Vi kan eksponere en egenskap som forteller om en eksamensdel er hoveddel eller forberedelse, men for eksempel Eksamen Del 1 og Eksamen Del 2 bil begge regnes som hoveddeler.

**Comment by espenekvang** [comment]
Et annet spørsmål:

**Eksamen.Eksamensdeler.Eksamensdel**
- Her vil det ligge dato og tidspunkt for gjennomføring, trenger dere da et eget felt som kun forteller datoen slik det er nå?

**Comment by aoksenholt** [comment]
**EksamensPeriode**

* Ved import av perioder fra PAS til SAS vil vi gjerne gjøre en sjekk av periode opp mot skoleår. Derfor ønskes det fra-til-dato for gjennomføring (første eksamensdag - siste eksamensdag).
Dette kan utledes fra eksamensdelene, men vil forenkles ved å ha datoer rett på perioden.

**Eksamen.Eksamensdeler.Eksamensdel**

* Type: OK.
* Hoveddel/forberedelse: Benyttes ved trekk til eksamen. Om EksamensdelType får en begrensning med kjente/gitte verdier kan eget felt for hoveddel/forberedelse utelates.
* Dato/tidspunkt: Fint slik dere har løst det nå (dato/tidspunkt i samme felt).

**Comment by espenekvang** [comment]
**EksamensPeriode**
- OK - da legger vi inn dato for gjennomføring også her

**Eksamen.Eksamensdeler.Eksamensdel**
- Flott
