### ISSUE TITLE
Schema for prøve api

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#76]
Vi får ApiError levert på spørringer mot ~/sas/proveoversikt, men ApiError er ikke en definert type i skjema fra https://proverapi-sas.udir.no/sas/schema

Er det tenkt at vi skal bruke typer eksamen api'et da vi lager integrasjonen for prøver?

Hvis det er type som er felles; kan det være en idé å skille de ut i noe som kan deles mellom integrasjonene?

**Comment by espenekvang** [comment]
Vi skal få lagt til ApiError i skjemaet. Det er en feil av oss at ikke det er lagt med. Det er ikke tenkt at dere skal benytte typer fra eksamen.

**Comment by thoraj** [comment]
OK, takk for svar..
