### ISSUE TITLE
Feilhåndtering

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#77]
Hei,

Forsøkte å melde på en prøvegruppe uten å autentisere, og fikk svar:

   `﻿<Error><Message>Authorization has been denied for this request.</Message></Error>`

Er dette korrekt, eller burde dette vært en ApiError?

**Comment by espenekvang** [comment]
Dette burde vært ApiError. Feilretting er gjort. Forventet å være på plass i testmiljøet i løpet av morgendagen.

**Comment by thoraj** [comment]
Takk.

Men ApiError finnes foreløpig ikke på "https://proverapi-sas.udir.no/sas/schema"
Jeg sjekker senere i dag.

**Comment by espenekvang** [comment]
Både endringen med `ApiError` på Unauthorized og XSD for denne er nå tilgjengelig i testmlijøet.
