### ISSUE TITLE
Feil ved henting av bearerToken

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#78]
Kode som fungerte i går gir i dag feilmelding:

`System.Security.Authentication.AuthenticationException : Could not aquire access token. Reason:Method Not Allowed, HttpStatusCode:MethodNotAllowed, HttpReason:Method Not Allowed`

Har det skjedd noe i testmiljøet?

**Comment by espenekvang** [comment]
Vi undersøker.

**Comment by thoraj** [comment]
Nevermind. 

Mea Culpa
