### ISSUE TITLE
ApiError respons

### ISSUE THREAD

**Issue by thoraj** [Utdanningsdirektoratet/PAS2-Public#79]
I prøve-api'et er ikke returnerte ApiError xml dokumenter (slik de var i eksamen). Det går greit å jobbe rundt dette ved å definere root element før deserialisering slik: 
`XmlRootAttribute apiErrorRoot = new XmlRootAttribute();
                    apiErrorRoot.ElementName = "ApiError";
                    apiErrorRoot.IsNullable = true;
                    var apiErrorSerializer = new XmlSerializer(typeof(ApiError), apiErrorRoot);
...
`
Men ønsker å vite om dette er tilsiktet?

**Comment by espenekvang** [comment]
Du skal ikke trenge å jobbe rundt det, vi har lagt til `XmlRoot` på `ApiError` slik som i eksamen. Det er rullet ut i testmiljøet.
