### ISSUE TITLE
Referanseimplementasjoner

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#8]
Har dere fått tid til å se noe på referanseimplementasjonen som vi har tilgjengeliggjort?
Når kan dere starte arbeide med å implementere deres klient mot vårt API slik at vi får klarhet i eventuelle problemstillinger relatert til sikkerhet etc? @aoksenholt

**Comment by aoksenholt** [comment]
Har implementer *innlogging*. Kan ikke se at det skal bli noen problemer slik dette er skissert.

**Comment by espenekvang** [comment]
Fint!
