### ISSUE TITLE
Grupper uten navn

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#87]
Vi har registrert at mange prøvegrupper som sendes inn ifm påmelding til prøver _ikke _ har spesifisert noe navn på gruppene. Grupper som ikke har navn vil få navnet _Mangler gruppenavn_ i systemet når de legges inn. Vi kommer ikke til å feile påmeldingen, men oppfordrer alle til å sikre at man sender inn gruppenavn med påmeldingen.

**Comment by AMNytroen** [comment]
Hei Espen

Har dere noen oversikt over hvilke skoler det dreier seg om, og som vi leverandørene kunne få oversikt over?
På den måten vil det være lettere for oss å kunne spore og finne avvikene!
Anne Mari


Best regards / Med vennlig hilsen
Anne Mari L Nytrøen
Service Manager

Tieto Norway
Mobile +47 40 21 57 21
E-mail: annemari.nytroen@tieto.com
Fra: Espen Ekvang [mailto:notifications@github.com]
Sendt: onsdag 15. mars 2017 12.58
Til: Utdanningsdirektoratet/PAS2-Public <PAS2-Public@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [Utdanningsdirektoratet/PAS2-Public] Grupper uten navn (#87)


Vi har registrert at mange prøvegrupper som sendes inn ifm påmelding til prøver _ikke _ har spesifisert noe navn på gruppene. Grupper som ikke har navn vil få navnet Mangler gruppenavn i systemet når de legges inn. Vi kommer ikke til å feile påmeldingen, men oppfordrer alle til å sikre at man sender inn gruppenavn med påmeldingen.

**Comment by espenekvang** [comment]
Vi har gått gjennom og vil ta direkte kontakt med de leverandørene dette gjelder.
