### ISSUE TITLE
Feil i prøveoversikt

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#88]
Det er oppdaget en feil i prøveoversikten. Feilen går på at det returneres en prøvetype som ikke er kommunisert at vi har lagt til. Vi jobber med å få ut en endring der denne prøvetypen ikke returneres ut til skoleadministrative systemer. I tillegg vil endringen inneholde oppdatert XSD som beskriver den nye prøvetypen `EP` som står for `Eksamensforberedende prøve`. Vi beklager eventuelle problemer dette har medført dere som leverandører av skoleadministrative systemer.

**Comment by AMNytroen** [comment]
Hei

Har dere trøbbel i produksjonsmiljøet i dag?
Flere av våre kunder får feil når de skal se aktive prøver…

Best regards / Med vennlig hilsen
Anne Mari L Nytrøen
Service Manager

Tieto Norway
Mobile +47 40 21 57 21
E-mail: annemari.nytroen@tieto.com
www.tieto.com / www.oppad.no<http://www.oppad.no>
[cid:9962E135-CA89-47E7-90C4-EB2F3BD7E9D8@eu.tieto.com]


 P   Ta miljøhensyn – vurder om du må skrive ut denne e-posten!

Fra: Espen Ekvang [mailto:notifications@github.com]
Sendt: mandag 20. mars 2017 21.00
Til: Utdanningsdirektoratet/PAS2-Public <PAS2-Public@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: Re: [Utdanningsdirektoratet/PAS2-Public] Feil i prøveoversikt (#88)


Oppdatert XSD for prøveoversikt er rullet ut i testmiljøet nå. (https://proverapi-sas.udir.no/sas/schema).
Vi forventer at denne oppdaterte XSD blir rullet ut i produksjonsmiljøet i morgen.

**Comment by espenekvang** [comment]
Ja, dessverre er det et problem med aktive prøver gjennom prøveoversikten. Vi jobber med å rette denne saken,

**Comment by espenekvang** [comment]
Prøven som skapte problemer med den nye prøvetypen er midlertidig fjernet fra systemet slik at det ikke skal skape mer problemer for dere.

**Comment by espenekvang** [comment]
I testmiljøet har vi nå oppdatert `https://proverapi-sas.udir.no/sas/proveoversikt` slik at man selv kan styre når man er klare for å ta imot prøvetypen `EP`. Når man har implementer endringene kan man spesifisere url-parameteren `nofilter=true` og man vil få ut alle prøvene inklusive `EP` dersom den er tilgjengelig for din skole. Det er forventet at denne funksjonaliteten blir produksjonssatt en av de første dagene.

**Comment by espenekvang** [comment]
Det er besluttet at prøvetypen `EP` blir utsatt og taes i bruk først neste år, altså våren 2018. Dette betyr at det ikke er kritisk å få dette raskt implementert for dere som leverandører, men at vi ønsker at dere skal legge inn støtte for denne prøvetypen.
