### ISSUE TITLE
[Test] Utvidelse av kontrakt

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#89]
Som vi har kommunisert på epost ønsker vi å undersøke muligheten for å kunne utvide enumverdier i kontraktn uten at vi må vente til alle leverandører er ferdig implementert før vi legger det ut.

Når har vi muliggjort testing av dette i testmiljøet (proverapi-sas.udir.no)
Dersom dere forsøker å melde på til NPLES08 og ikke setter avgiverskole i påmeldingen vil den påmeldte eleven få en ny status i påmeldingsrapporten som dere kan hente ut etter innsendt på melding. Den nye statusen er `PameldtManglerAvgiverskole`.

**Comment by thomashannestad** [comment]
Hvilket orgnr og skoleår skal vi benytte for å importere NPLES08?

Med vennlig hilsen
Thomas Hannestad
Barman Hanssen AS
thomas@barman-hanssen.no

**Comment by espenekvang** [comment]
Testmiljøet har de samme skolene som ligger i Produksjonsmiljøet. Du trenger en skole som er gyldig for 8.trinn siden prøven er definert for det. Dersom du kan benytte en av deres "egne" skoler er det det beste.

**Comment by thomashannestad** [comment]
Først trodde vi det var snakk om å akseptere nye attributter, men etter å ha lest opprinnelig melding på nytt, ser vi at det er snakk om nye enum-verdier. Første problemstilling fant vi en løsning på, men enum’en ser ut til å være vanskeligere. Noen som har fått til å håndtere den? 

Vi benytter XML og JAXBContext / Unmarshaller. Lar dette seg bedre løse med JSON? 

Dette er feilmeldingen vi får:
DefaultValidationEventHandler: [ERROR]: 
Exception Description: No conversion value provided for the value [PameldtManglerAvgiverskole] in field [Status/text()].
Mapping: org.eclipse.persistence.oxm.mappings.XMLDirectMapping[status-->Status/text()]
Descriptor: XMLDescriptor(bh.iSkole.eksamen.view.beans.pas.prover.pamelding.ElevReportType --> []) 
     Location: line 1

Med vennlig hilsen
Thomas Hannestad
Barman Hanssen AS
thomas@barman-hanssen.no

**Comment by espenekvang** [comment]
Takk for tilbakemeldingen.
