### ISSUE TITLE
Brukere i PAS2

### ISSUE THREAD

**Issue by aoksenholt** [Utdanningsdirektoratet/PAS2-Public#9]
Vil brukere/brukernavn (som sendes med i payload) være like/det samme i PAS1 og PAS2?

**Comment by espenekvang** [comment]
Nei, det vil det ikke være. Vi skal undersøke hva dette brukernavnet brukes til i PAS1. Dersom det kun er der for å kunne sende ut epost vil vi vurdere at epostadressen heller spesifiseres som en del av payloaden i stedet for brukernavnet, gitt at vi skal sende ut epost om status.

**Comment by espenekvang** [comment]
Det er nå lagt inn mulighet for å spesifisere at man ønsker en epost dersom påmeldingen feiler. Påmeldingen er utvidet til å kunne ta imot et felt som heter EpostadresseVedFeil. Feltet er ikke obligatorisk, men dersom man spesifiserer en adresse her vil PAS sende ut en epost til den adressen dersom påmeldingen feiler.
