### ISSUE TITLE
Publisering av eksamensplaner

### ISSUE THREAD

**Issue by espenekvang** [Utdanningsdirektoratet/PAS2-Public#90]
Det gjøres et arbeid for å kunne styre publisering av eksamensplaner i PAS-Eksamen. Dette betyr at innholdet man får ut på ressursen `~/api/ekstern/eksamensplan` vil få høyere grad av dynamisk innhold når Utdanningsdirektoratet jobber med disse planene. De vil få muligheten til å endre allerede publiserte eksamensplaner.

En ting vi lurer på er hvordan de skoleadministrative systemene vil forholde seg til om vi åpner for funksjonalitet for å avpublisere en plan? Dvs. som et SAS kan du da risikere at en plan "forsvinner" fra ressursen som et resultat av at man har valgt å avpublisere en eksamensplan. Er dette noe som kan skape utfordringer for dere, eller er det greit? Dette har altså ingenting med kontrakten å gjøre, men med selve innholdet. Det gjelder også fremtidige eksamensplaner selvfølgelig.

**Comment by thomashannestad** [comment]
Siden vi tidligere har opplevd innholdet som relativt statisk, blir dette kun hentet inn en gang. Skolene har hatt mulighet til å "manuelt" oppdatere planen dersom de vet noe nytt er kommet til. Da har vi lagt til nye planer eventuelt oppdatert eksisterende. Vi har ikke tatt høyde for at planer kan "forsvinne". Dersom dere ønsker at planer dere sletter også skal slettes hos oss, så kan vi løse dette ved å slette alle planene og lese inn de nye. Dette vil fortsatt forutsette at skolen velger å oppdatere planene. 

Dersom dere legger til en webservice som forteller oss når siste endring av eksamensplanene er gjort, så kan vi gjøre en sjekk mot denne datoen hver gang(evt. begrense til en gang om dagen) skolen skal legge inn et eksamensparti. Dersom det er gjort endringer siden planene sist ble lastet inn, så sletter vi planene og leser inn på nytt. Det blir vel unødvendig mye trafikk dersom vi ukritisk skal hente alle planene hver gang de jobber med eksamenspartiene?

Alternativt kunne vi sendt inn datoen vi sist hentet planer og kun mottatt endringene, men da må det gjøres noe kreativt for de planene som forsvinner.

**Comment by WISole** [comment]
Vi har lagt opp til at skolen kan laste ned oppdatert plan når som helst, og det gjøres vel når skolen ikke finner aktuell plan ved påmelding. Tidligere nedlastet plan blir da erstattet. Klarer ikke å se at det vil ha noen konsekvens for oss om en plan "forsvinner" fra ressursen.
