### ISSUE TITLE
Ny ressurs for sletting av påmeldt kandidat

### ISSUE THREAD

**Issue by thereseblom** [Utdanningsdirektoratet/PAS2-Public#92]
Vi holder på å implementere en ny ressurs for å kunne slette en påmeldt kandidat: **~/kandidat/{kandidatnummer}/fagkode/{fagkode}?orgno={orgno}&periodekode={periodekode}**
Se Wiki for ytterligere detaljer. Dette er et pågående arbeide og ressursen kan foreløpig nås i testmiljøet. Den er ikke ferdig implementert og det vil derfor ikke være mulig å slette med det første, kun teste at ressursen kan nås.

**Comment by Sigve-** [comment]
Kode for å slette flere kandidater er straks i test. 
HttpDelete på ressursen 
~/kandidat?orgno={orgno}&periodekode={periodekode}
FormData:
	[
		{
			Kandidatnummer: "1234",
			Fagkode: "NOR-1415"
		}	,
			{
			Kandidatnummer: "1234",
			Fagkode: "NOR-1415"
		}
	]

**Comment by jorjoh** [comment]
Denne funksjonaliteten finnes nå i produksjon
