### ISSUE TITLE
Fagkoder eksamensplan grunnskole

### ISSUE THREAD

**Issue by AMNytroen** [Utdanningsdirektoratet/PAS2-Public#93]
Er det noen årsak til til at fagkodene vi henter via eksamensplan grunnskole inneholder både fagkodene til de sentralt gitte eksamenene og  til lokalt avholdte eksamener? 

Er det noen måte å skille på fagkoer knyttet til sentralt hhv lokalt gitt eksamen i API'et, slik av vi ved oppmelding av elever til skriftlig eksamen grunnskole bare kan hente de korrekte fagkoder?

**Comment by thereseblom** [comment]
Hei,
Om du har filtrert på grunnskole som opplæringsnivå skal du ikke få lokalt gitte eksamener.
Hvis dette er tilfelle hadde det vært fint om du kom med et eksempel så kan vi undersøke nærmere.

**Comment by AMNytroen** [comment]
Kallet «sas/eksamensplan?opplaeringsniva=GS» returnerer følgende fagkoder i drift:
SFS0012
NOR1415
NORV012
SAS0012
FIN0012
SAS0025
MATV005
NOR0214
SFS0025
NOR0052
NOR0215
MATV004
MAT0010
NOR0041
ENGV005
NORV005
SFS0038
NOR0064
SAS0038
MATV006
ENG0012

Og disse i test:

ENG0012
ENG0025
FIN0012
MAT0010
NOR0041
NOR0214
NOR0215
NOR1415
SAS0012
SAS0025
SAS0038
SFS0012
SFS0025
SFS0038
TST1003
TST1004


Anne Mari L Nytrøen
Service Manager
Tieto Education Norway

**Comment by thereseblom** [comment]
@AMNytroen hvilke fagkoder i produksjon er det du ikke ville hatt der? Alle 21 fagkoder skal være sentralt gitte og skriftlige.

**Comment by AMNytroen** [comment]
Jeg har vært av den oppfatning at skolene bare skulle melde opp til  NOR0214, NOR0215, NOR1415, ENG0012, MAT0010
men det er kanskje sånn at øvrige koder soom starter med NOR, SAS, SFS og FIN er i alternativer til NOR0214 eller NOR0215?

Anne Mari L Nytrøen
Service Manager
Tieto Education Norway

**Comment by thereseblom** [comment]
@AMNytroen Det stemmer at de fleste kun blir meldt opp i NOR0214, NOR0215, NOR1415, ENG0012, MAT0010. Men det skal også være mulig å melde opp kandidater i de resterende fagkodene. De fagkodene som har en V i seg gjelder voksenopplæring og det skal skolene ha blitt informert om.

**Comment by AMNytroen** [comment]
Takk

Anne Mari L Nytrøen
Service Manager
Tieto Education Norway
