### ISSUE TITLE
Henting av sensoroppdrag for en skole

### ISSUE THREAD

**Issue by HalldisBekk** [Utdanningsdirektoratet/PAS2-Public#94]
Vi jobber med å implementere en ny ressurs for å hente alle fagpersoner som er oppnevnt som sensor eller klagenemndsmedlem ved en skole: **~sensoroppdrag/{organisasjonsnummer}/{eksamensperiodekode}**
Se Wiki for ytterligere detaljer. 

Endringene er nå ute i test

**Comment by thereseblom** [comment]
Ressursen er nå tilgjengelig i produksjon
