### ISSUE TITLE
SasStatus - nytt felt i Påmeldingsrapport

### ISSUE THREAD

**Issue by Henriksive** [Utdanningsdirektoratet/PAS2-Public#97]
### Beskrivelse
I forbindelse med nye rutiner rundt at en skole skal registrere hvilket SAS skolen bruker, legges det til et nytt felt i følgende endepunkt:

### Endepunkter
GET ~/sas/pamelding/{pameldingsref}

**Dokumentasjon PAS – prøver:**
https://proverapi-sas.udir.no/swagger/ui/index#!/SAS_-_Skoleadministrative_systemer/Pamelding_GetPameldingReportAsync

**Dokumentasjon PAS – eksamen:**
https://eksamenapi-sas.udir.no/swagger/ui/index#/SAS324532Skoleadministrative32systemer
### Nytt felt
Hensikten med feltet er å informere SASene om påmeldinger som er blitt midlertidig stanset som følge av at SASet ikke er blitt registrert av skolen. 

Det nye feltet vil hete `SasStatus` og være en del av responsen fra endepunktet.
`SasStatus` vil være av typen `string` og kan inneholde følgende verdier: 
 - `Ok` -> SASet som skolen har registrert samsvarer med det SASet som utførte påmeldingen. 
 - `ManglerSas` -> Skolen har ikke registrert et SAS. Påmeldingen vil bli godkjent dersom skolen registrerer SASet som ble brukt for å gjennomføre påmeldingen. 
 - `FeilSas` -> Skolen har registrert et annet SAS en det som ble brukt til å utføre påmeldingen. Påmeldingen vil bli godkjent dersom skolen registrerer SASet som ble brukt for å gjennomføre påmeldingen.
 - `Avvist` -> Påmeldingen er avvist og vil ikke bli gjennomført.

#### PAS – eksamen:
Tilgjengelig i SAS test:                             21. august
Produksjonsettes:                                    26. august

#### PAS – prøver:
Tilgjengelig i SAS Test:                             30. september
Produksjonsettes:                                     14. oktober

**Comment by mhjelmseth** [comment]
Hei

Vi holder på med å impelmentere dette i Visma FLYT Skole, i første omgang for eksamen.

Er det mulig for dere å opprette en eksamenplan for GS for periode H-2019 på https://eksamen-sas.udir.no? Dette hadde gjort det enklere for oss ved testing.

mvh
Morten Hjelmseth
Visma Software Labs AS

**Comment by thereseblom** [comment]
Hei,

Det finnes ingen eksamensplan for grunnskole for høsten (grunnskole har kun vår). Jeg har opprettet eksamensplanen for våren 2019, hjelper det?

Hilsen
Therese
Utvikler PAS-eksamen

**Comment by mhjelmseth** [comment]
Ok, jeg forstår. Men kan fortsatt ikke finne noen for GS på periode V-2019?

curl -X GET --header 'Accept: application/json' 'https://eksamenapi-sas.udir.no/sas/eksamensplan?eksamensperiode=V-2019&opplaeringsniva=GS'

**Comment by thereseblom** [comment]
Nå skal den være der, hadde glemt å publisere den :)

**Comment by mhjelmseth** [comment]
Ser bedre ut nå, @thereseblom. Takk :)

**Comment by mhjelmseth** [comment]
Nytt spm. til verdien FeilSas. 

Jeg går ut ifra at det er klientsertifikatet som benyttes ved pålogging som bestemmer hva slags SAS påmeldingene kommer ifra. Stemmer dette? I såfall, hvordan registerer skolene hvilket SAS og klientsertifikat de bruker? Visma FLYT skole benytter samme klientsertifikat for alle skoler, og skolene har ikke noe forhold til dette.

mvh
Morten Hjelmseth
Visma FLYT Skole

**Comment by thereseblom** [comment]
Hei igjen,

Ja, det stemmer. Rent teknisk sjekker vi at organisasjonsnummeret i klientsertifikatet stemmer overens med organisasjonsnummeret til SASet som skolen har registrert. Skolen forholder seg kun til hvilket SAS de har og registrerer dette ved å velge i en liste med navn over tilgjengelige SAS.

**Comment by mhjelmseth** [comment]
Takk for svar :)
